<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/rival_ui.php';
require_once __DIR__ . '/includes/bot_runtime.php';
pv_require_login();
$db=pv_db();$now=time();$ready=pv_rival_ready($db);$feed=[];$top=[];$zones=[];$stats=['bots'=>0,'ranked24'=>0,'wild24'=>0,'captures24'=>0,'evolutions24'=>0,'top_rating'=>0];
if($ready){
    pv_rival_ensure_all_states($db); pv_rival_housekeeping($db); pv_bot_tick($db,24,'','',45); $now=time();
    $r=$db->query('SELECT COUNT(*) c FROM bot_trainers WHERE enabled=1');if($r){$stats['bots']=(int)($r->fetch_assoc()['c']??0);$r->free();}
    $since=$now-86400;
    $r=$db->query("SELECT SUM(category='ranked') ranked24,SUM(category='wild') wild24,SUM(category='capture') captures24,SUM(category='evolution') evolutions24 FROM ai_activity WHERE created_at>=".(int)$since);if($r){$x=$r->fetch_assoc()?:[];$stats['ranked24']=(int)($x['ranked24']??0);$stats['wild24']=(int)($x['wild24']??0);$stats['captures24']=(int)($x['captures24']??0);$stats['evolutions24']=(int)($x['evolutions24']??0);$r->free();}
    $r=$db->query('SELECT MAX(rs.rating) top_rating FROM trainer_rank_state rs JOIN bot_trainers b ON b.user_id=rs.user_id AND b.enabled=1');if($r){$stats['top_rating']=(int)($r->fetch_assoc()['top_rating']??0);$r->free();}
    $r=$db->query("SELECT a.*,m.username,rs.rating,rs.ranked_wins,rs.ranked_losses,rs.current_streak,b.bot_index,b.trainer_sprite,b.world_key,b.map_key,p.name lead_name,1 is_bot FROM ai_activity a JOIN members m ON m.id=a.bot_user_id JOIN bot_trainers b ON b.user_id=a.bot_user_id AND b.enabled=1 JOIN trainer_rank_state rs ON rs.user_id=a.bot_user_id LEFT JOIN pokemon p ON p.id=m.s1 AND CAST(p.owner AS UNSIGNED)=m.id ORDER BY a.id DESC LIMIT 90"); if($r){$feed=$r->fetch_all(MYSQLI_ASSOC);$r->free();}
    $r=$db->query("SELECT rs.*,m.username,b.bot_index,b.trainer_sprite,b.world_key,b.map_key,p.name lead_name,1 is_bot FROM trainer_rank_state rs JOIN members m ON m.id=rs.user_id JOIN bot_trainers b ON b.user_id=rs.user_id AND b.enabled=1 LEFT JOIN pokemon p ON p.id=m.s1 AND CAST(p.owner AS UNSIGNED)=m.id ORDER BY rs.rating DESC,rs.ranked_wins DESC LIMIT 12");if($r){$top=$r->fetch_all(MYSQLI_ASSOC);$r->free();}
    $r=$db->query("SELECT UPPER(world_key) world,COUNT(*) bots,SUM(last_action_at>=".(int)($now-3600).") active_hour,SUM(captures) captures,SUM(wild_battles) wild_battles FROM bot_trainers WHERE enabled=1 GROUP BY world_key ORDER BY bots DESC");if($r){$zones=$r->fetch_all(MYSQLI_ASSOC);$r->free();}
}
$categoryIcons=['ranked'=>'images/items/Ultra Ball.png','capture'=>'images/items/Poke Ball.png','wild'=>'images/pokemon/Pikachu.gif','evolution'=>'images/items/Master Ball.png','roam'=>'images/items/Great Ball.png'];
pv_page_start('AI Activity','ai_activity.php',true);
?>
<div class="pv-game-layout"><?php pv_game_side_menu('ai_activity.php'); ?><main class="pv-main-column"><section class="pv-page pv-ai-activity-page">
<?php pv_pokemon_banner('AUTONOMOUS TRAINER FIELD','AI Activity','Persistent AI trainers keep exploring, catching Pokémon, fighting wild encounters and pressing the ranked ladder even when no player is watching the world.',['Metagross','Gengar','Blastoise','Treecko','Torchic']); ?>
<?php if(!$ready):?><div class="pv-flash warning"><strong>AI Activity is waiting to be activated.</strong><span>Open Setup and run Upgrade once to bring the Rival Network activity feed online.</span></div><?php else:?>
<section class="pv-ai-kpis"><article><img src="<?=pv_h(pv_static_file('images/items/Poke Ball.png','images/Pokeball.PNG'))?>" alt=""><span>AI TRAINERS ONLINE</span><strong><?=number_format($stats['bots'])?></strong><small>persistent autonomous population</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Ultra Ball.png','images/Pokeball.PNG'))?>" alt=""><span>RANKED OPERATIONS · 24H</span><strong><?=number_format($stats['ranked24'])?></strong><small>ladder pressure while players are away</small></article><article><img src="<?=pv_h(pv_static_file('images/pokemon/Pikachu.gif','images/Pokeball.PNG'))?>" alt=""><span>WILD TRAINING · 24H</span><strong><?=number_format($stats['wild24'])?></strong><small>persisted encounter outcomes</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Great Ball.png','images/Pokeball.PNG'))?>" alt=""><span>CAPTURES · 24H</span><strong><?=number_format($stats['captures24'])?></strong><small>new Pokémon added by AI</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Master Ball.png','images/Pokeball.PNG'))?>" alt=""><span>EVOLUTIONS · 24H</span><strong><?=number_format($stats['evolutions24'])?></strong><small>level-driven team evolution</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Master Ball.png','images/Pokeball.PNG'))?>" alt=""><span>TOP AI RATING</span><strong><?=number_format($stats['top_rating'])?></strong><small>current autonomous benchmark</small></article></section>

<section class="pv-ai-zone-strip"><div class="pv-rival-section-head"><div><span class="pv-eyebrow">WORLD POPULATION SCAN</span><h2>Autonomous Training Zones</h2></div><span class="pv-rival-scanner"><i></i> LIVE FIELD</span></div><div class="pv-ai-zone-grid"><?php foreach($zones as $z):?><article><img src="<?=pv_h(pv_static_file('images/items/Poke Ball.png','images/Pokeball.PNG'))?>" alt=""><div><span><?=pv_h((string)$z['world'])?></span><strong><?=number_format((int)$z['bots'])?> trainers</strong><small><?=number_format((int)$z['active_hour'])?> active this hour · <?=number_format((int)$z['captures'])?> total catches</small></div><i><b style="width:<?=min(100,max(4,(int)round(((int)$z['active_hour']/max(1,(int)$z['bots']))*100)))?>%"></b></i></article><?php endforeach;?></div></section>

<section class="pv-ai-layout"><div class="pv-ai-feed-panel"><div class="pv-rival-section-head"><div><span class="pv-eyebrow">LATEST AUTONOMOUS EVENTS</span><h2>AI Activity Feed</h2><p>The feed records meaningful ranked, capture, wild-battle and sampled roaming events—not every background tick.</p></div><span class="pv-rival-section-count"><?=count($feed)?> EVENTS</span></div>
<?php if($feed):?><div class="pv-ai-feed"><?php foreach($feed as $row):$rating=(int)$row['rating'];$tier=pv_rival_tier($rating);$trainer=pv_rival_trainer_sprite($row);$activityProfile=pv_bot_activity_profile((int)$row['bot_index']);$icon=$categoryIcons[(string)$row['category']]??'images/items/Poke Ball.png';?><article class="pv-ai-event pv-ai-event-<?=pv_h((string)$row['category'])?>"><div class="pv-ai-event-icon"><img src="<?=pv_h(pv_static_file($icon,'images/items/Poke Ball.png'))?>" alt=""></div><a class="pv-ai-event-trainer" href="<?=pv_h(pv_url('bot_trainer.php?id='.(int)$row['bot_user_id']))?>"><span><img class="trainer" src="<?=pv_h(pv_static_file('images/sprites/'.$trainer.'whole.gif','images/sprites/1whole.gif'))?>" alt=""><img class="lead" src="<?=pv_h(pv_rival_lead_url($row))?>" alt=""></span><strong><?=pv_h((string)$row['username'])?></strong><small><?=pv_h((string)$activityProfile['label'])?> · AI #<?=str_pad((string)(int)$row['bot_index'],4,'0',STR_PAD_LEFT)?> · <?=pv_h(strtoupper((string)$row['world_key']))?> / <?=pv_h((string)$row['map_key'])?></small></a><div class="pv-ai-event-copy"><strong><?=pv_h((string)$row['headline'])?></strong><span><?=pv_h((string)$row['detail'])?></span></div><div class="pv-ai-event-rank"><span class="pv-rival-tier pv-tier-<?=pv_h((string)$tier['class'])?>"><img src="<?=pv_h(pv_rival_ball_url($rating))?>" alt=""><?=pv_h((string)$tier['short'])?></span><strong><?=number_format($rating)?> RP</strong><?php if((int)$row['rating_delta']!==0):?><b class="<?=(int)$row['rating_delta']>0?'positive':'negative'?>"><?=(int)$row['rating_delta']>0?'+':''?><?=number_format((int)$row['rating_delta'])?></b><?php endif;?><small><?=pv_h(pv_rival_time_ago((int)$row['created_at'],$now))?></small></div></article><?php endforeach;?></div><?php else:?><div class="pv-empty-state"><strong>Activity feed is warming up.</strong><span>Autonomous trainers will add events as world and ranked operations resolve.</span></div><?php endif;?></div>
<aside class="pv-ai-pressure-panel"><div class="pv-rival-section-head"><div><span class="pv-eyebrow">LADDER PRESSURE</span><h2>Top AI Rivals</h2></div><a href="<?=pv_h(pv_url('rankings.php?scope=ai'))?>">Full AI ladder →</a></div><div class="pv-ai-top-list"><?php foreach($top as $index=>$row):$rating=(int)$row['rating'];$tier=pv_rival_tier($rating);$activityProfile=pv_bot_activity_profile((int)$row['bot_index']);?><a href="<?=pv_h(pv_url('bot_trainer.php?id='.(int)$row['user_id']))?>"><span class="rank">#<?=($index+1)?></span><span class="sprite"><img src="<?=pv_h(pv_rival_lead_url($row))?>" alt=""></span><span class="name"><strong><?=pv_h((string)$row['username'])?></strong><small><?=pv_h((string)$activityProfile['label'])?> · <?=number_format((int)$row['ranked_wins'])?> W · <?=number_format((int)$row['ranked_losses'])?> L</small></span><span class="rating"><img src="<?=pv_h(pv_rival_ball_url($rating))?>" alt=""><strong><?=number_format($rating)?></strong></span></a><?php endforeach;?></div></aside></section>
<?php endif;?></section></main></div><?php pv_page_end(); ?>
