<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/rival_ui.php';
require_once __DIR__ . '/includes/bot_runtime.php';
pv_require_login();
// Feed filters use fixed SQL fragments; query-string text never enters SQL.
$filters=[
    'all'=>['label'=>'All events','where'=>'1=1'],
    'wild'=>['label'=>'Wild battles','where'=>"a.category='wild'"],
    'wild_wins'=>['label'=>'Wild wins','where'=>"a.category='wild' AND a.headline='Won a wild battle'"],
    'wild_losses'=>['label'=>'Wild losses','where'=>"a.category='wild' AND a.headline='Lost a wild battle'"],
    'capture'=>['label'=>'Catches','where'=>"a.category='capture'"],
    'ranked'=>['label'=>'Ranked','where'=>"a.category='ranked'"],
];
$requestedFilter=$_GET['activity']??'all';
$filter=is_string($requestedFilter)&&isset($filters[$requestedFilter])?$requestedFilter:'all';
$db=pv_db();$now=time();$ready=pv_rival_ready($db);$feed=[];$top=[];$zones=[];
$stats=['bots'=>0,'ranked'=>0,'wild'=>0,'wild_wins'=>0,'wild_losses'=>0,'captures'=>0,'evolutions'=>0,'top_rating'=>0];
if($ready){
    pv_rival_ensure_all_states($db); pv_rival_housekeeping($db); pv_bot_tick($db,24,'','',45); $now=time();
    $r=$db->query('SELECT COUNT(*) c FROM bot_trainers WHERE enabled=1');if($r){$stats['bots']=(int)($r->fetch_assoc()['c']??0);$r->free();}
    // This table is a bounded rolling feed, not a complete 24-hour ledger.
    $r=$db->query("SELECT SUM(category='ranked') ranked,SUM(category='wild') wild,SUM(category='wild' AND headline='Won a wild battle') wild_wins,SUM(category='wild' AND headline='Lost a wild battle') wild_losses,SUM(category='capture') captures,SUM(category='evolution') evolutions FROM ai_activity");
    if($r){$x=$r->fetch_assoc()?:[];foreach(['ranked','wild','wild_wins','wild_losses','captures','evolutions'] as $key)$stats[$key]=(int)($x[$key]??0);$r->free();}
    $r=$db->query('SELECT MAX(rs.rating) top_rating FROM trainer_rank_state rs JOIN bot_trainers b ON b.user_id=rs.user_id AND b.enabled=1');if($r){$stats['top_rating']=(int)($r->fetch_assoc()['top_rating']??0);$r->free();}
    $r=$db->query("SELECT a.*,m.username,rs.rating,rs.ranked_wins,rs.ranked_losses,rs.current_streak,b.bot_index,b.trainer_sprite,b.world_key,b.map_key,p.name lead_name,1 is_bot FROM ai_activity a JOIN members m ON m.id=a.bot_user_id JOIN bot_trainers b ON b.user_id=a.bot_user_id AND b.enabled=1 JOIN trainer_rank_state rs ON rs.user_id=a.bot_user_id LEFT JOIN pokemon p ON p.id=m.s1 AND CAST(p.owner AS UNSIGNED)=m.id WHERE ".$filters[$filter]['where']." ORDER BY a.id DESC LIMIT 90"); if($r){$feed=$r->fetch_all(MYSQLI_ASSOC);$r->free();}
    $r=$db->query("SELECT rs.*,m.username,b.bot_index,b.trainer_sprite,b.world_key,b.map_key,p.name lead_name,1 is_bot FROM trainer_rank_state rs JOIN members m ON m.id=rs.user_id JOIN bot_trainers b ON b.user_id=rs.user_id AND b.enabled=1 LEFT JOIN pokemon p ON p.id=m.s1 AND CAST(p.owner AS UNSIGNED)=m.id ORDER BY rs.rating DESC,rs.ranked_wins DESC,rs.ranked_losses ASC,rs.user_id ASC LIMIT 12");if($r){$top=$r->fetch_all(MYSQLI_ASSOC);$r->free();}
    $r=$db->query("SELECT UPPER(world_key) world,COUNT(*) bots,SUM(last_action_at>=".(int)($now-3600).") active_hour,SUM(captures) captures,SUM(wild_battles) wild_battles FROM bot_trainers WHERE enabled=1 GROUP BY world_key ORDER BY bots DESC");if($r){$zones=$r->fetch_all(MYSQLI_ASSOC);$r->free();}
}
$categoryIcons=['ranked'=>'images/items/Ultra Ball.png','capture'=>'images/items/Poke Ball.png','wild'=>'images/pokemon/Pikachu.gif','evolution'=>'images/items/Master Ball.png','roam'=>'images/items/Great Ball.png'];
pv_page_start('AI Activity','ai_activity.php',true);
?>
<div class="pv-game-layout"><?php pv_game_side_menu('ai_activity.php'); ?><main class="pv-main-column"><section class="pv-page pv-ai-activity-page">
<?php pv_pokemon_banner('AUTONOMOUS TRAINER FIELD','AI Activity','Persistent AI trainers keep exploring, catching Pokémon, fighting wild encounters and pressing the ranked ladder even when no player is watching the world.',['Metagross','Gengar','Blastoise','Treecko','Torchic']); ?>
<?php if(!$ready):?><div class="pv-flash warning"><strong>AI Activity is waiting to be activated.</strong><span>Open Setup and run Upgrade once to bring the Rival Network activity feed online.</span></div><?php else:?>
<section class="pv-ai-kpis"><article><img src="<?=pv_h(pv_static_file('images/items/Poke Ball.png','images/Pokeball.PNG'))?>" alt=""><span>AI TRAINERS ENABLED</span><strong><?=number_format($stats['bots'])?></strong><small>registered autonomous population</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Ultra Ball.png','images/Pokeball.PNG'))?>" alt=""><span>RECENT RANKED BATTLES</span><strong><?=number_format($stats['ranked'])?></strong><small>ranked events in retained history</small></article><article><img src="<?=pv_h(pv_static_file('images/pokemon/Pikachu.gif','images/Pokeball.PNG'))?>" alt=""><span>RECENT WILD BATTLES</span><strong><?=number_format($stats['wild'])?></strong><small><?=number_format($stats['wild_wins'])?> wins · <?=number_format($stats['wild_losses'])?> losses</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Great Ball.png','images/Pokeball.PNG'))?>" alt=""><span>RECENT CATCHES</span><strong><?=number_format($stats['captures'])?></strong><small>includes caught and released Pokémon</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Master Ball.png','images/Pokeball.PNG'))?>" alt=""><span>RECENT EVOLUTIONS</span><strong><?=number_format($stats['evolutions'])?></strong><small>evolution events in retained history</small></article><article><img src="<?=pv_h(pv_static_file('images/items/Master Ball.png','images/Pokeball.PNG'))?>" alt=""><span>TOP AI RATING</span><strong><?=number_format($stats['top_rating'])?></strong><small>current autonomous benchmark</small></article></section>

<section class="pv-ai-zone-strip"><div class="pv-rival-section-head"><div><span class="pv-eyebrow">WORLD POPULATION SCAN</span><h2>Autonomous Training Zones</h2></div><span class="pv-rival-scanner"><i></i> LIVE FIELD</span></div><div class="pv-ai-zone-grid"><?php foreach($zones as $z):?><article><img src="<?=pv_h(pv_static_file('images/items/Poke Ball.png','images/Pokeball.PNG'))?>" alt=""><div><span><?=pv_h((string)$z['world'])?></span><strong><?=number_format((int)$z['bots'])?> trainers</strong><small><?=number_format((int)$z['active_hour'])?> active this hour · <?=number_format((int)$z['captures'])?> total catches</small></div><i><b style="width:<?=min(100,max(4,(int)round(((int)$z['active_hour']/max(1,(int)$z['bots']))*100)))?>%"></b></i></article><?php endforeach;?></div></section>

<section class="pv-ai-layout"><div class="pv-ai-feed-panel"><div class="pv-rival-section-head"><div><span class="pv-eyebrow">LATEST AUTONOMOUS EVENTS</span><h2>AI Activity Feed</h2><p>Recent counts cover retained events. Use the filters to inspect wild wins, losses, catches and ranked battles. Trainer profiles keep lifetime records.</p></div><span class="pv-rival-section-count"><?=count($feed)?> EVENTS</span></div>
<nav class="pv-ranking-filters pv-actions" aria-label="AI activity filters">
<?php foreach($filters as $key=>$option):?><a class="<?=$filter===$key?'active':''?>"<?=$filter===$key?' aria-current="page"':''?> href="<?=pv_h(pv_url('ai_activity.php?activity='.$key))?>"><?=pv_h($option['label'])?></a><?php endforeach;?>
</nav>
<?php if($feed):?><div class="pv-ai-feed"><?php foreach($feed as $row):$rating=(int)$row['rating'];$tier=pv_rival_tier($rating);$trainer=pv_rival_trainer_sprite($row);$activityProfile=pv_bot_activity_profile((int)$row['bot_index']);$icon=$categoryIcons[(string)$row['category']]??'images/items/Poke Ball.png';?><article class="pv-ai-event pv-ai-event-<?=pv_h((string)$row['category'])?>"><div class="pv-ai-event-icon"><img src="<?=pv_h(pv_static_file($icon,'images/items/Poke Ball.png'))?>" alt=""></div><a class="pv-ai-event-trainer" href="<?=pv_h(pv_url('bot_trainer.php?id='.(int)$row['bot_user_id']))?>"><span><img class="trainer" src="<?=pv_h(pv_static_file('images/sprites/'.$trainer.'whole.gif','images/sprites/1whole.gif'))?>" alt=""><img class="lead" src="<?=pv_h(pv_rival_lead_url($row))?>" alt=""></span><strong><?=pv_h((string)$row['username'])?></strong><small><?=pv_h((string)$activityProfile['label'])?> · AI #<?=str_pad((string)(int)$row['bot_index'],4,'0',STR_PAD_LEFT)?> · <?=pv_h(strtoupper((string)$row['world_key']))?> / <?=pv_h((string)$row['map_key'])?></small></a><div class="pv-ai-event-copy"><strong><?=pv_h((string)$row['headline'])?></strong><span><?=pv_h((string)$row['detail'])?></span></div><div class="pv-ai-event-rank"><span class="pv-rival-tier pv-tier-<?=pv_h((string)$tier['class'])?>"><img src="<?=pv_h(pv_rival_ball_url($rating))?>" alt=""><?=pv_h((string)$tier['short'])?></span><strong><?=number_format($rating)?> RP</strong><?php if((int)$row['rating_delta']!==0):?><b class="<?=(int)$row['rating_delta']>0?'positive':'negative'?>"><?=(int)$row['rating_delta']>0?'+':''?><?=number_format((int)$row['rating_delta'])?></b><?php endif;?><small><?=pv_h(pv_rival_time_ago((int)$row['created_at'],$now))?></small></div></article><?php endforeach;?></div><?php else:?><div class="pv-empty-state"><strong>No <?=pv_h(strtolower($filters[$filter]['label']))?> in the retained feed.</strong><span>Completed events appear here as the AI service runs. Older events may have left the rolling feed; trainer profiles retain their totals.</span></div><?php endif;?></div>
<aside class="pv-ai-pressure-panel"><div class="pv-rival-section-head"><div><span class="pv-eyebrow">LADDER PRESSURE</span><h2>Top AI Rivals</h2></div><a href="<?=pv_h(pv_url('rankings.php?scope=ai'))?>">Full AI ladder →</a></div><div class="pv-ai-top-list"><?php foreach($top as $index=>$row):$rating=(int)$row['rating'];$tier=pv_rival_tier($rating);$activityProfile=pv_bot_activity_profile((int)$row['bot_index']);?><a href="<?=pv_h(pv_url('bot_trainer.php?id='.(int)$row['user_id']))?>"><span class="rank">#<?=($index+1)?></span><span class="sprite"><img src="<?=pv_h(pv_rival_lead_url($row))?>" alt=""></span><span class="name"><strong><?=pv_h((string)$row['username'])?></strong><small><?=pv_h((string)$activityProfile['label'])?> · <?=number_format((int)$row['ranked_wins'])?> W · <?=number_format((int)$row['ranked_losses'])?> L</small></span><span class="rating"><img src="<?=pv_h(pv_rival_ball_url($rating))?>" alt=""><strong><?=number_format($rating)?></strong></span></a><?php endforeach;?></div></aside></section>
<?php endif;?></section></main></div><?php pv_page_end(); ?>
