<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/network.php';
require_once __DIR__ . '/includes/ui.php';
pv_require_login();
$db=pv_db();$uid=(int)$_SESSION['myid'];

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        pv_require_csrf();$action=(string)($_POST['action']??'');
        if($action==='create'){pv_clan_create($db,$uid,(string)($_POST['name']??''),(string)($_POST['tag']??''),(string)($_POST['motto']??''));$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'Clan created successfully.'];}
        elseif($action==='apply'){pv_clan_apply($db,$uid,max(0,(int)($_POST['clan_id']??0)));$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'Clan application submitted.'];}
        elseif($action==='accept'||$action==='decline'){pv_clan_resolve_application($db,$uid,max(0,(int)($_POST['application_id']??0)),$action==='accept'?'accepted':'declined');$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'Clan application updated.'];}
        elseif($action==='leave'){pv_clan_leave($db,$uid);$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'You left the clan.'];}
        elseif($action==='remove'){pv_clan_remove_member($db,$uid,max(0,(int)($_POST['member_id']??0)));$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'Clan member removed.'];}
        elseif($action==='transfer'){pv_clan_transfer($db,$uid,max(0,(int)($_POST['member_id']??0)));$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'Clan leadership transferred.'];}
        elseif($action==='disband'){if(strtoupper(trim((string)($_POST['confirm']??'')))!=='DISBAND')throw new RuntimeException('Type DISBAND to confirm this permanent action.');pv_clan_disband($db,$uid);$_SESSION['pv_clan_flash']=['type'=>'success','text'=>'The clan was disbanded.'];}
        else throw new RuntimeException('Choose a clan action.');
    }catch(RuntimeException $e){$_SESSION['pv_clan_flash']=['type'=>'error','text'=>$e->getMessage()];}
    pv_redirect('clans.php');
}
$flash=$_SESSION['pv_clan_flash']??null;unset($_SESSION['pv_clan_flash']);
$current=pv_clan_current($db,$uid);$showCreate=isset($_GET['create'])&&!$current;
$clans=[];$stmt=$db->prepare('SELECT id,name,tag,motto,owner,points,exp,wins,losses,members FROM clans ORDER BY points DESC,exp DESC,name ASC LIMIT 100');if($stmt){$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$clans[]=$row;$stmt->close();}

pv_page_start('Clans','community.php',true);
?>
<div class="pv-game-layout"><?php pv_game_side_menu('clans.php');?><main class="pv-main-column"><section class="pv-page pv-clans-page">
<div class="pv-page-head"><div><span class="pv-eyebrow">TRAINER HUB // CLANS</span><h1>Clans</h1><p class="pv-subtle">Build a trainer group, recruit members and grow your clan together.</p></div><?php if(!$current):?><a class="pv-button" href="<?=pv_h(pv_url('clans.php?create=1'))?>">Create Clan</a><?php endif;?></div>
<?php if(is_array($flash)):?><div class="pv-alert pv-alert-<?=pv_h((string)$flash['type'])?>"><?=pv_h((string)$flash['text'])?></div><?php endif;?>
<?php if($current):
$clanId=(int)$current['clan_id'];$members=[];$stmt=$db->prepare('SELECT cm.id,cm.username,cm.owner,cm.exp,m.battle,m.points FROM clan_members cm LEFT JOIN members m ON m.id=cm.id WHERE cm.clan_id=? ORDER BY cm.owner DESC,cm.exp DESC,cm.username');if($stmt){$stmt->bind_param('i',$clanId);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$members[]=$row;$stmt->close();}
$apps=[];if((int)$current['is_owner']){$stmt=$db->prepare("SELECT ca.id,ca.user_id,ca.created_at,m.username,m.points,m.battle FROM clan_applications ca JOIN members m ON m.id=ca.user_id WHERE ca.clan_id=? AND ca.status='pending' ORDER BY ca.id ASC");if($stmt){$stmt->bind_param('i',$clanId);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$apps[]=$row;$stmt->close();}}
?>
<section class="pv-clan-hero"><div class="pv-clan-emblem"><?=pv_h(strtoupper((string)$current['tag']))?></div><div><small>CLAN // <?=pv_h(strtoupper((string)$current['tag']))?></small><h2><?=pv_h((string)$current['name'])?></h2><p><?=pv_h((string)($current['motto']?:'No clan motto has been set.'))?></p><span>Leader: <?=pv_h((string)$current['owner_name'])?></span></div><div class="pv-clan-rank"><small>CLAN POINTS</small><strong><?=number_format((int)$current['points'])?></strong></div></section>
<div class="pv-stat-grid"><div><span>Members</span><strong><?=number_format(count($members))?></strong></div><div><span>Clan EXP</span><strong><?=number_format((int)$current['exp'])?></strong></div><div><span>Wins</span><strong><?=number_format((int)$current['wins'])?></strong></div><div><span>Losses</span><strong><?=number_format((int)$current['losses'])?></strong></div></div>
<section class="pv-card"><span class="pv-eyebrow">CLAN ROSTER</span><div class="pv-clan-roster"><?php foreach($members as $m):?><div><a href="<?=pv_h(pv_url('members.php?profile='.(int)$m['id']))?>"><span class="pv-trainer-avatar small"><?=pv_h(strtoupper(mb_substr((string)$m['username'],0,1)))?></span><div><strong><?=pv_h((string)$m['username'])?></strong><small><?=((int)$m['owner'])?'CLAN LEADER':number_format((int)$m['exp']).' EXP CONTRIBUTION'?></small></div></a><div class="pv-actions"><?php if((int)$current['is_owner'] && (int)$m['id']!==$uid):?><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="transfer"><input type="hidden" name="member_id" value="<?=(int)$m['id']?>"><button class="pv-button-secondary" type="submit">Make Leader</button></form><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="remove"><input type="hidden" name="member_id" value="<?=(int)$m['id']?>"><button class="pv-button-danger" type="submit">Remove</button></form><?php endif;?></div></div><?php endforeach;?></div></section>
<?php if((int)$current['is_owner']):?><section class="pv-card"><span class="pv-eyebrow">RECRUITMENT QUEUE</span><?php if(!$apps):?><p class="pv-subtle">No pending applications.</p><?php else:?><div class="pv-request-list"><?php foreach($apps as $a):?><div><a href="<?=pv_h(pv_url('members.php?profile='.(int)$a['user_id']))?>"><strong><?=pv_h((string)$a['username'])?></strong><span><?=number_format((int)$a['battle'])?> wins · <?=number_format((int)$a['points'])?> points</span></a><div class="pv-actions"><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="accept"><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><button type="submit">Accept</button></form><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="decline"><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><button class="pv-button-secondary" type="submit">Decline</button></form></div></div><?php endforeach;?></div><?php endif;?></section><?php endif;?>
<section class="pv-card pv-clan-controls"><span class="pv-eyebrow">CLAN CONTROL</span><?php if((int)$current['is_owner']):?><p>Transfer leadership before leaving, or permanently disband the clan.</p><form method="post" class="pv-disband-form"><?=pv_csrf_field()?><input type="hidden" name="action" value="disband"><label><span>Type DISBAND to confirm</span><input name="confirm" autocomplete="off" placeholder="DISBAND"></label><button class="pv-button-danger" type="submit">Disband Clan</button></form><?php else:?><p>You can leave this clan at any time. Your Pokémon and trainer progression are unaffected.</p><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="leave"><button class="pv-button-danger" type="submit">Leave Clan</button></form><?php endif;?></section>
<?php elseif($showCreate):?>
<section class="pv-form-card pv-clan-create"><span class="pv-eyebrow">NEW CLAN REGISTRATION</span><h2>Create Clan</h2><p class="pv-subtle">Choose a distinct name and compact tag. Clan creation is immediate.</p><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="create"><div class="pv-field"><label>Clan name</label><input name="name" maxlength="45" minlength="3" required></div><div class="pv-field"><label>Clan tag <small>2–6 letters or numbers</small></label><input name="tag" maxlength="6" pattern="[A-Za-z0-9]{2,6}" required></div><div class="pv-field"><label>Motto</label><input name="motto" maxlength="180"></div><div class="pv-actions"><button type="submit">Create Clan</button><a class="pv-button pv-button-secondary" href="<?=pv_h(pv_url('clans.php'))?>">Cancel</a></div></form></section>
<?php else:?>
<div class="pv-clan-directory"><?php foreach($clans as $rank=>$c):?><article class="pv-clan-directory-card"><div class="pv-clan-emblem small"><?=pv_h(strtoupper((string)$c['tag']))?></div><div><small>RANK <?=str_pad((string)($rank+1),2,'0',STR_PAD_LEFT)?></small><h3><?=pv_h((string)$c['name'])?></h3><p><?=pv_h((string)($c['motto']?:'Open clan registry entry'))?></p><span><?=number_format((int)$c['members'])?> members · <?=number_format((int)$c['points'])?> points · leader <?=pv_h((string)$c['owner'])?></span></div><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="apply"><input type="hidden" name="clan_id" value="<?=(int)$c['id']?>"><button type="submit">Apply</button></form></article><?php endforeach;?></div><?php if(!$clans):?><div class="pv-empty-state"><span class="pv-brand-mark">CL</span><div><h2>No clans registered</h2><p>Create the first clan.</p><a class="pv-button" href="<?=pv_h(pv_url('clans.php?create=1'))?>">Create Clan</a></div></div><?php endif;?>
<?php endif;?>
</section></main></div>
<?php pv_page_end(); ?>
