<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/network.php';
require_once __DIR__ . '/includes/rival_ui.php';
pv_require_login();
$db=pv_db();$uid=(int)$_SESSION['myid'];

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        pv_require_csrf();$action=(string)($_POST['action']??'');$target=max(0,(int)($_POST['target_id']??0));
        if($action==='friend')pv_network_friend_request($db,$uid,$target);
        elseif($action==='remove_friend')pv_network_remove_friend($db,$uid,$target);
        elseif($action==='block')pv_network_block($db,$uid,$target);
        elseif($action==='unblock')pv_network_unblock($db,$uid,$target);
        elseif($action==='request_accept'||$action==='request_decline'){ $request=max(0,(int)($_POST['request_id']??0));pv_network_resolve_friend_request($db,$uid,$request,$action==='request_accept'?'accepted':'declined'); }
        else throw new RuntimeException('Choose a trainer-network action.');
        $_SESSION['pv_network_flash']=['type'=>'success','text'=>'Trainer network updated successfully.'];
    }catch(RuntimeException $e){$_SESSION['pv_network_flash']=['type'=>'error','text'=>$e->getMessage()];}
    $back=max(0,(int)($_POST['profile_id']??0));pv_redirect('members.php'.($back?'?profile='.$back:''));
}
$flash=$_SESSION['pv_network_flash']??null;unset($_SESSION['pv_network_flash']);
$profileId=max(0,(int)($_GET['profile']??0));

pv_page_start('Trainers','community.php',true);
?>
<div class="pv-game-layout"><?php pv_game_side_menu('members.php');?><main class="pv-main-column"><section class="pv-page pv-trainers-page">
<?php if($profileId>0):
    $profile=pv_network_user($db,$profileId);$profileTrainer=1;if($profile){$stmt=$db->prepare('SELECT trainer FROM members_options WHERE id=? LIMIT 1');if($stmt){$stmt->bind_param('i',$profileId);$stmt->execute();$opt=$stmt->get_result()->fetch_assoc();$stmt->close();$profileTrainer=max(1,min(40,(int)($opt['trainer']??1)));}}
    if(!$profile):?><div class="pv-empty-state"><span class="pv-brand-mark">?</span><div><h2>Trainer not found</h2><p>This trainer record is unavailable.</p><a class="pv-button" href="<?=pv_h(pv_url('members.php'))?>">Trainer Directory</a></div></div>
    <?php else:
        $friend=pv_network_are_friends($db,$uid,$profileId);$blockedByMe=false;$stmt=$db->prepare('SELECT 1 FROM trainer_blocks WHERE user_id=? AND blocked_user_id=? LIMIT 1');if($stmt){$stmt->bind_param('ii',$uid,$profileId);$stmt->execute();$blockedByMe=(bool)$stmt->get_result()->fetch_row();$stmt->close();}
        $online=false;if(pv_table_exists('online')){$cut=time()-900;$stmt=$db->prepare('SELECT 1 FROM online WHERE username=? AND CAST(time AS UNSIGNED)>=? LIMIT 1');if($stmt){$name=(string)$profile['username'];$stmt->bind_param('si',$name,$cut);$stmt->execute();$online=(bool)$stmt->get_result()->fetch_row();$stmt->close();}}
        $team=[];$stmt=$db->prepare('SELECT s1,s2,s3,s4,s5,s6 FROM members WHERE id=? LIMIT 1');if($stmt){$stmt->bind_param('i',$profileId);$stmt->execute();$slots=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();foreach(range(1,6) as $n){$pid=(int)($slots['s'.$n]??0);if($pid>0){$stmt=$db->prepare("SELECT p.name,p.lvl,COALESCE(ps.display_form,'') display_form FROM pokemon p LEFT JOIN pokemon_stats ps ON ps.id=p.id WHERE p.id=? LIMIT 1");if($stmt){$stmt->bind_param('i',$pid);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();$stmt->close();if($row)$team[]=$row;}}}}
    ?>
    <div class="pv-page-head"><div><span class="pv-eyebrow">TRAINER PROFILE // #<?=$profileId?></span><h1><?=pv_h((string)$profile['username'])?></h1><p class="pv-subtle"><?=$online?'Online on the trainer network':'Currently offline'?><?=trim((string)$profile['clan_name'])!==''?' · Clan '.pv_h((string)$profile['clan_name']):''?></p></div><a class="pv-button pv-button-secondary" href="<?=pv_h(pv_url('members.php'))?>">Trainer Directory</a></div>
    <?php if(is_array($flash)):?><div class="pv-alert pv-alert-<?=pv_h((string)$flash['type'])?>"><?=pv_h((string)$flash['text'])?></div><?php endif;?>
    <div class="pv-trainer-profile-grid"><section class="pv-card pv-trainer-identity"><div class="pv-trainer-avatar"><img src="<?=pv_h(pv_static_file('images/sprites/'.$profileTrainer.'whole.gif','images/sprites/1whole.gif'))?>" alt="<?=pv_h((string)$profile['username'])?>"></div><div><span class="pv-status-pill <?=$online?'online':''?>"><?=$online?'ONLINE':'OFFLINE'?></span><h2><?=pv_h((string)$profile['username'])?></h2><p><?=trim((string)$profile['clan_name'])!==''?'['.pv_h((string)$profile['clan_tag']).'] '.pv_h((string)$profile['clan_name']):'Independent trainer'?></p></div></section><section class="pv-card"><div class="pv-stat-grid"><div><span>Battle wins</span><strong><?=number_format((int)$profile['battle'])?></strong></div><div><span>Battle losses</span><strong><?=number_format((int)$profile['losses'])?></strong></div><div><span>Pokémon</span><strong><?=number_format((int)$profile['total_poke'])?></strong></div><div><span>Trainer points</span><strong><?=number_format((int)$profile['points'])?></strong></div></div></section></div>
    <?php pv_rival_profile_panel($db, $profileId, $uid); ?>
    <section class="pv-card"><span class="pv-eyebrow">ACTIVE TEAM</span><div class="pv-team"><?php if(!$team):?><p class="pv-subtle">No public active team is available.</p><?php else:foreach($team as $p):$d=trim((string)$p['display_form'])?: (string)$p['name'];?><div class="pv-pokemon-card"><img src="<?=pv_h(pv_pokemon_sprite($d))?>" alt="<?=pv_h($d)?>"><strong><?=pv_h($d)?></strong><small>Lv. <?=number_format((int)$p['lvl'])?></small></div><?php endforeach;endif;?></div></section>
    <?php if($profileId!==$uid):?><section class="pv-card"><span class="pv-eyebrow">TRAINER ACTIONS</span><div class="pv-actions"><?php if($blockedByMe):?><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="unblock"><input type="hidden" name="target_id" value="<?=$profileId?>"><input type="hidden" name="profile_id" value="<?=$profileId?>"><button type="submit">Unblock Trainer</button></form><?php else:?><?php if($friend):?><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="remove_friend"><input type="hidden" name="target_id" value="<?=$profileId?>"><input type="hidden" name="profile_id" value="<?=$profileId?>"><button type="submit" class="pv-button-secondary">Remove Friend</button></form><?php else:?><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="friend"><input type="hidden" name="target_id" value="<?=$profileId?>"><input type="hidden" name="profile_id" value="<?=$profileId?>"><button type="submit">Send Friend Request</button></form><?php endif;?><a class="pv-button pv-button-secondary" href="<?=pv_h(pv_url('messages.php?box=compose&to='.rawurlencode((string)$profile['username'])))?>">Message</a><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="block"><input type="hidden" name="target_id" value="<?=$profileId?>"><input type="hidden" name="profile_id" value="<?=$profileId?>"><button class="pv-button-danger" type="submit">Block</button></form><?php endif;?></div></section><?php endif;?>
    <?php endif;?>
<?php else:
    $q=trim((string)($_GET['q']??''));$rows=[];$sql='SELECT m.id,m.username,m.clan_name,m.clan_tag,m.battle,m.losses,m.points,m.total_poke,m.totalexp,COALESCE(o.trainer,1) AS trainer FROM members m LEFT JOIN members_options o ON o.id=m.id WHERE m.id<>?';$types='i';$args=[$uid];if($q!==''){$sql.=' AND m.username LIKE ?';$types.='s';$args[]='%'.$q.'%';}$sql.=' ORDER BY m.points DESC,m.battle DESC,m.username ASC LIMIT 120';$stmt=$db->prepare($sql);if($stmt){$stmt->bind_param($types,...$args);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$rows[]=$row;$stmt->close();}
    $requests=[];$stmt=$db->prepare("SELECT fr.id,fr.sender_id,m.username,fr.created_at FROM friend_requests fr JOIN members m ON m.id=fr.sender_id WHERE fr.receiver_id=? AND fr.status='pending' ORDER BY fr.id DESC LIMIT 20");if($stmt){$stmt->bind_param('i',$uid);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$requests[]=$row;$stmt->close();}
    $friends=[];$stmt=$db->prepare('SELECT f.friend_id,m.username,m.clan_tag,m.points FROM trainer_friends f JOIN members m ON m.id=f.friend_id WHERE f.user_id=? ORDER BY m.username LIMIT 80');if($stmt){$stmt->bind_param('i',$uid);$stmt->execute();$r=$stmt->get_result();while($row=$r->fetch_assoc())$friends[]=$row;$stmt->close();}
?>
<div class="pv-page-head"><div><span class="pv-eyebrow">TRAINER DIRECTORY</span><h1>Trainers</h1><p class="pv-subtle">Find trainers, add friends and manage requests.</p></div><a class="pv-button pv-button-secondary" href="<?=pv_h(pv_url('community.php'))?>">Community Hub</a></div>
<?php if(is_array($flash)):?><div class="pv-alert pv-alert-<?=pv_h((string)$flash['type'])?>"><?=pv_h((string)$flash['text'])?></div><?php endif;?>
<?php if($requests):?><section class="pv-card"><span class="pv-eyebrow">PENDING FRIEND REQUESTS</span><div class="pv-request-list"><?php foreach($requests as $req):?><div><a href="<?=pv_h(pv_url('members.php?profile='.(int)$req['sender_id']))?>"><strong><?=pv_h((string)$req['username'])?></strong><span><?=date('j M H:i',(int)$req['created_at'])?> UTC</span></a><div class="pv-actions"><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="request_accept"><input type="hidden" name="request_id" value="<?=(int)$req['id']?>"><button type="submit">Accept</button></form><form method="post"><?=pv_csrf_field()?><input type="hidden" name="action" value="request_decline"><input type="hidden" name="request_id" value="<?=(int)$req['id']?>"><button type="submit" class="pv-button-secondary">Decline</button></form></div></div><?php endforeach;?></div></section><?php endif;?>
<div class="pv-network-summary"><section class="pv-card"><span class="pv-eyebrow">FRIENDS</span><strong class="pv-big-number"><?=number_format(count($friends))?></strong><p>Trainers on your friends list.</p></section><section class="pv-card"><span class="pv-eyebrow">DIRECTORY RESULTS</span><strong class="pv-big-number"><?=number_format(count($rows))?></strong><p>Ranked trainers matching the current search.</p></section></div>
<form method="get" class="pv-dex-search"><input name="q" value="<?=pv_h($q)?>" placeholder="Search trainer name"><button type="submit">Search</button><?php if($q!==''):?><a href="<?=pv_h(pv_url('members.php'))?>">Clear</a><?php endif;?></form>
<div class="pv-trainer-grid"><?php foreach($rows as $u):$isFriend=pv_network_are_friends($db,$uid,(int)$u['id']);?><a class="pv-trainer-card <?=$isFriend?'is-friend':''?>" href="<?=pv_h(pv_url('members.php?profile='.(int)$u['id']))?>"><div class="pv-trainer-avatar"><img src="<?=pv_h(pv_static_file('images/sprites/'.max(1,min(40,(int)($u['trainer']??1))).'whole.gif','images/sprites/1whole.gif'))?>" alt="<?=pv_h((string)$u['username'])?>"></div><div><small><?=trim((string)$u['clan_tag'])!==''?'['.pv_h((string)$u['clan_tag']).']':'TRAINER'?></small><h3><?=pv_h((string)$u['username'])?></h3><span><?=number_format((int)$u['battle'])?> wins · <?=number_format((int)$u['points'])?> points</span></div><b><?=$isFriend?'FRIEND':'›'?></b></a><?php endforeach;?></div>
<?php endif;?>
</section></main></div>
<?php pv_page_end(); ?>
