<?php
declare(strict_types=1);

/**
 * v22.4.0 authoritative reconstructed league/facility catalog.
 * IDs 1..95 deliberately map to badges.g1..g95 and historical battle routes.
 * The 99 visible legacy cards contain 95 unique progression identities because
 * the Indigo Elite Four are shared by Kanto and Johto.
 */
function pv_battle_catalog(): array
{
    static $catalog = null;
    if ($catalog !== null) return $catalog;
    $catalog = [
        1 => [
            'route' => 'Brock',
            'display' => 'Brock',
            'venue' => 'Pewter City Gym',
            'reward' => 'Boulder Badge',
            'sprite' => 'brock.gif',
            'badge' => 'boulder.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 12,
            'roster' => ['Geodude', 'Onix'],
        ],
        2 => [
            'route' => 'Misty',
            'display' => 'Misty',
            'venue' => 'Cerulean City Gym',
            'reward' => 'Cascade Badge',
            'sprite' => 'misty.gif',
            'badge' => 'cascade.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 20,
            'roster' => ['Staryu', 'Starmie', 'Gyarados'],
        ],
        3 => [
            'route' => 'Lt. Surge',
            'display' => 'Lt. Surge',
            'venue' => 'Vermilion City Gym',
            'reward' => 'Thunder Badge',
            'sprite' => 'lt. surge.gif',
            'badge' => 'thunder.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 28,
            'roster' => ['Pikachu', 'Voltorb', 'Raichu', 'Electrode'],
        ],
        4 => [
            'route' => 'Erika',
            'display' => 'Erika',
            'venue' => 'Celadon City Gym',
            'reward' => 'Rainbow Badge',
            'sprite' => 'erika.gif',
            'badge' => 'rainbow.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 36,
            'roster' => ['Victreebel', 'Tangela', 'Vileplume', 'Venusaur'],
        ],
        5 => [
            'route' => 'Sabrina',
            'display' => 'Sabrina',
            'venue' => 'Saffron City Gym',
            'reward' => 'Marsh Badge',
            'sprite' => 'sabrina.gif',
            'badge' => 'marsh.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 44,
            'roster' => ['Kadabra', 'Haunter', 'Mr. Mime', 'Venomoth', 'Alakazam'],
        ],
        6 => [
            'route' => 'Janine',
            'display' => 'Janine',
            'venue' => 'Fuchsia City Gym',
            'reward' => 'Soul Badge',
            'sprite' => 'janine.gif',
            'badge' => 'soul.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 50,
            'roster' => ['Nidoqueen', 'Koffing', 'Grimer', 'Muk', 'Weezing'],
        ],
        7 => [
            'route' => 'Blaine',
            'display' => 'Blaine',
            'venue' => 'Cinnabar Island Gym',
            'reward' => 'Volcano Badge',
            'sprite' => 'blaine.gif',
            'badge' => 'volcano.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 56,
            'roster' => ['Growlithe', 'Ponyta', 'Charmeleon', 'Rapidash', 'Magmar', 'Arcanine'],
        ],
        8 => [
            'route' => 'Giovanni',
            'display' => 'Giovanni',
            'venue' => 'Viridian City Gym',
            'reward' => 'Earth Badge',
            'sprite' => 'giovanni.gif',
            'badge' => 'earth.gif',
            'division' => 'Gym Leader',
            'region' => 'Kanto',
            'level' => 62,
            'roster' => ['Rhyhorn', 'Dugtrio', 'Rhydon', 'Golem', 'Nidoqueen', 'Nidoking'],
        ],
        9 => [
            'route' => 'Cissy',
            'display' => 'Cissy',
            'venue' => 'Mikan Island Gym',
            'reward' => 'Coral Eye Badge',
            'sprite' => 'cissy.gif',
            'badge' => 'coral.gif',
            'division' => 'Orange Crew',
            'region' => 'Orange Islands',
            'level' => 35,
            'roster' => ['Seadra', 'Blastoise'],
        ],
        10 => [
            'route' => 'Danny',
            'display' => 'Danny',
            'venue' => 'Navel Island Gym',
            'reward' => 'Sea Ruby Badge',
            'sprite' => 'danny.gif',
            'badge' => 'ruby.gif',
            'division' => 'Orange Crew',
            'region' => 'Orange Islands',
            'level' => 42,
            'roster' => ['Nidoqueen', 'Machoke', 'Scyther', 'Electrode', 'Geodude'],
        ],
        11 => [
            'route' => 'Rudy',
            'display' => 'Rudy',
            'venue' => 'Trovita Gym',
            'reward' => 'Spike Shell Badge',
            'sprite' => 'rudy.gif',
            'badge' => 'spike.gif',
            'division' => 'Orange Crew',
            'region' => 'Orange Islands',
            'level' => 48,
            'roster' => ['Electabuzz', 'Exeggutor', 'Starmie', 'Hitmonchan', 'Ninetales'],
        ],
        12 => [
            'route' => 'Luana',
            'display' => 'Luana',
            'venue' => 'Kumquat Gym',
            'reward' => 'Jade Star Badge',
            'sprite' => 'luana.gif',
            'badge' => 'jade.gif',
            'division' => 'Orange Crew',
            'region' => 'Orange Islands',
            'level' => 54,
            'roster' => ['Alakazam', 'Marowak'],
        ],
        13 => [
            'route' => 'Champion Drake',
            'display' => 'Drake',
            'venue' => 'Pummelo Stadium',
            'reward' => 'Winners Trophy',
            'sprite' => 'championdrake.gif',
            'badge' => 'winners trophy.gif',
            'division' => 'Orange Champion',
            'region' => 'Orange Islands',
            'level' => 62,
            'roster' => ['Ditto', 'Onix', 'Gengar', 'Electabuzz', 'Venusaur', 'Dragonite'],
        ],
        14 => [
            'route' => 'Falkner',
            'display' => 'Falkner',
            'venue' => 'Violet City Gym',
            'reward' => 'Zephyr Badge',
            'sprite' => 'falkner.gif',
            'badge' => 'zephyr.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 12,
            'roster' => ['Pidgey', 'Pidgeotto'],
        ],
        15 => [
            'route' => 'Bugsy',
            'display' => 'Bugsy',
            'venue' => 'Azalea Town Gym',
            'reward' => 'Hive Badge',
            'sprite' => 'bugsy.gif',
            'badge' => 'hive.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 18,
            'roster' => ['Metapod', 'Kakuna', 'Scyther'],
        ],
        16 => [
            'route' => 'Whitney',
            'display' => 'Whitney',
            'venue' => 'Goldenrod City Gym',
            'reward' => 'Plain Badge',
            'sprite' => 'whitney.gif',
            'badge' => 'plain.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 24,
            'roster' => ['Clefairy', 'Jigglypuff', 'Miltank'],
        ],
        17 => [
            'route' => 'Morty',
            'display' => 'Morty',
            'venue' => 'Ecruteak City Gym',
            'reward' => 'Fog Badge',
            'sprite' => 'morty.gif',
            'badge' => 'fog.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 30,
            'roster' => ['Gastly', 'Haunter', 'Gengar', 'Haunter'],
        ],
        18 => [
            'route' => 'Chuck',
            'display' => 'Chuck',
            'venue' => 'Cianwood City Gym',
            'reward' => 'Storm Badge',
            'sprite' => 'chuck.gif',
            'badge' => 'storm.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 36,
            'roster' => ['Poliwhirl', 'Poliwrath', 'Primeape'],
        ],
        19 => [
            'route' => 'Jasmine',
            'display' => 'Jasmine',
            'venue' => 'Olivine City Gym',
            'reward' => 'Mineral Badge',
            'sprite' => 'jasmine.gif',
            'badge' => 'mineral.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 42,
            'roster' => ['Magnemite', 'Magneton', 'Magnemite', 'Steelix'],
        ],
        20 => [
            'route' => 'Pryce',
            'display' => 'Pryce',
            'venue' => 'Mahogany City Gym',
            'reward' => 'Glacier Badge',
            'sprite' => 'pryce.gif',
            'badge' => 'glacier.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 48,
            'roster' => ['Seel', 'Jynx', 'Dewgong', 'Seel', 'Piloswine'],
        ],
        21 => [
            'route' => 'Clair',
            'display' => 'Clair',
            'venue' => 'Blackthorn City Gym',
            'reward' => 'Rising Badge',
            'sprite' => 'clair.gif',
            'badge' => 'rising.gif',
            'division' => 'Gym Leader',
            'region' => 'Johto',
            'level' => 54,
            'roster' => ['Dragonair', 'Dratini', 'Dragonite', 'Dragonair', 'Dragonite', 'Kingdra'],
        ],
        22 => [
            'route' => 'Roxanne',
            'display' => 'Roxanne',
            'venue' => 'Rustboro City Gym',
            'reward' => 'Stone Badge',
            'sprite' => 'roxanne.gif',
            'badge' => 'stone.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 15,
            'roster' => ['Geodude', 'Nosepass'],
        ],
        23 => [
            'route' => 'Brawly',
            'display' => 'Brawly',
            'venue' => 'Dewford Town Gym',
            'reward' => 'Knuckle Badge',
            'sprite' => 'brawly.gif',
            'badge' => 'knuckle.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 20,
            'roster' => ['Machop', 'Makuhita'],
        ],
        24 => [
            'route' => 'Wattson',
            'display' => 'Wattson',
            'venue' => 'Mauville City Gym',
            'reward' => 'Dynamo Badge',
            'sprite' => 'wattson.gif',
            'badge' => 'dynamo.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 25,
            'roster' => ['Magnemite', 'Manectric', 'Magneton'],
        ],
        25 => [
            'route' => 'Flannery',
            'display' => 'Flannery',
            'venue' => 'Lavaridge City Gym',
            'reward' => 'Heat Badge',
            'sprite' => 'flannery.gif',
            'badge' => 'heat.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 30,
            'roster' => ['Slugma', 'Magcargo', 'Torkoal', 'Camerupt'],
        ],
        26 => [
            'route' => 'Norman',
            'display' => 'Norman',
            'venue' => 'Petalburg City Gym',
            'reward' => 'Balance Badge',
            'sprite' => 'norman.gif',
            'badge' => 'balance.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 35,
            'roster' => ['Vigoroth', 'Zangoose', 'Vigoroth', 'Slaking'],
        ],
        27 => [
            'route' => 'Winona',
            'display' => 'Winona',
            'venue' => 'Fortree City Gym',
            'reward' => 'Feather Badge',
            'sprite' => 'winona.gif',
            'badge' => 'feather.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 40,
            'roster' => ['Skarmory', 'Tropius', 'Swellow', 'Pelipper', 'Altaria'],
        ],
        28 => [
            'route' => 'Liza and Tate',
            'display' => 'Liza and Tate',
            'venue' => 'Mossdeep City Gym',
            'reward' => 'Mind Badge',
            'sprite' => 'lizaandtate.gif',
            'badge' => 'mind.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 45,
            'roster' => ['Xatu', 'Xatu', 'Solrock', 'Lunatone', 'Claydol'],
        ],
        29 => [
            'route' => 'Wallace',
            'display' => 'Wallace',
            'venue' => 'Hoenn Champion',
            'reward' => 'Hoenn League Champion',
            'sprite' => 'wallace.gif',
            'badge' => '',
            'division' => 'Champion',
            'region' => 'Hoenn',
            'level' => 65,
            'roster' => ['Seaking', 'Tentacruel', 'Seaking', 'Lapras', 'Gyarados', 'Milotic'],
        ],
        30 => [
            'route' => 'Roark',
            'display' => 'Roark',
            'venue' => 'Oreburgh City Gym',
            'reward' => 'Coal Badge',
            'sprite' => 'roark.gif',
            'badge' => 'coal.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 15,
            'roster' => ['Geodude', 'Onix', 'Cranidos'],
        ],
        31 => [
            'route' => 'Gardenia',
            'display' => 'Gardenia',
            'venue' => 'Eterna City Gym',
            'reward' => 'Forest Badge',
            'sprite' => 'gardenia.gif',
            'badge' => 'forest.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 21,
            'roster' => ['Cherubi', 'Turtwig', 'Roserade'],
        ],
        32 => [
            'route' => 'Maylene',
            'display' => 'Maylene',
            'venue' => 'Veilstone City Gym',
            'reward' => 'Cobble Badge',
            'sprite' => 'maylene.gif',
            'badge' => 'cobble.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 27,
            'roster' => ['Meditite', 'Machoke', 'Lucario'],
        ],
        33 => [
            'route' => 'Wake',
            'display' => 'Crasher Wake',
            'venue' => 'Pastoria City Gym',
            'reward' => 'Fen Badge',
            'sprite' => 'wake.gif',
            'badge' => 'fen.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 33,
            'roster' => ['Gyarados', 'Quagsire', 'Floatzel'],
        ],
        34 => [
            'route' => 'Fantina',
            'display' => 'Fantina',
            'venue' => 'Hearthome City Gym',
            'reward' => 'Relic Badge',
            'sprite' => 'fantina.gif',
            'badge' => 'relic.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 39,
            'roster' => ['Haunter', 'Drifblim', 'Gengar', 'Mismagius'],
        ],
        35 => [
            'route' => 'Byron',
            'display' => 'Byron',
            'venue' => 'Canalave City Gym',
            'reward' => 'Mine Badge',
            'sprite' => 'byron.gif',
            'badge' => 'mine.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 45,
            'roster' => ['Onix', 'Bronzor', 'Steelix', 'Bastiodon'],
        ],
        36 => [
            'route' => 'Candice',
            'display' => 'Candice',
            'venue' => 'Snowpoint City Gym',
            'reward' => 'Icicle Badge',
            'sprite' => 'candice.gif',
            'badge' => 'icicle.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 51,
            'roster' => ['Sneasel', 'Weavile', 'Snover', 'Medicham', 'Abomasnow'],
        ],
        37 => [
            'route' => 'Volkner',
            'display' => 'Volkner',
            'venue' => 'Sunyshore City Gym',
            'reward' => 'Beacon Badge',
            'sprite' => 'volkner.gif',
            'badge' => 'beacon.gif',
            'division' => 'Gym Leader',
            'region' => 'Sinnoh',
            'level' => 57,
            'roster' => ['Pikachu', 'Luxio', 'Raichu', 'Ambipom', 'Octillery', 'Luxray'],
        ],
        38 => [
            'route' => 'Cheren',
            'display' => 'Cheren',
            'venue' => 'Aspertia City Gym',
            'reward' => 'Basic Badge',
            'sprite' => 'cheren.gif',
            'badge' => 'basic.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 15,
            'roster' => ['Patrat', 'Pidove', 'Lillipup'],
        ],
        39 => [
            'route' => 'Roxie',
            'display' => 'Roxie',
            'venue' => 'Virbank City Gym',
            'reward' => 'Toxic Badge',
            'sprite' => 'roxie.gif',
            'badge' => 'toxic.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 21,
            'roster' => ['Koffing', 'Grimer', 'Whirlipede'],
        ],
        40 => [
            'route' => 'Burgh',
            'display' => 'Burgh',
            'venue' => 'Castelia City Gym',
            'reward' => 'Insect Badge',
            'sprite' => 'burgh.gif',
            'badge' => 'insect.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 27,
            'roster' => ['Dwebble', 'Shelmet', 'Karrablast', 'Leavanny'],
        ],
        41 => [
            'route' => 'Elesa',
            'display' => 'Elesa',
            'venue' => 'Nimbasa City Gym',
            'reward' => 'Bolt Badge',
            'sprite' => 'elesa.gif',
            'badge' => 'bolt.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 33,
            'roster' => ['Emolga', 'Flaaffy', 'Joltik', 'Zebstrika'],
        ],
        42 => [
            'route' => 'Clay',
            'display' => 'Clay',
            'venue' => 'Driftveil City Gym',
            'reward' => 'Quake Badge',
            'sprite' => 'clay.gif',
            'badge' => 'quake.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 39,
            'roster' => ['Krokorok', 'Sandslash', 'Onix', 'Excadrill'],
        ],
        43 => [
            'route' => 'Skyla',
            'display' => 'Skyla',
            'venue' => 'Mistralton City Gym',
            'reward' => 'Jet Badge',
            'sprite' => 'skyla.gif',
            'badge' => 'jet.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 45,
            'roster' => ['Swoobat', 'Skarmory', 'Sigilyph', 'Swanna'],
        ],
        44 => [
            'route' => 'Drayden',
            'display' => 'Drayden',
            'venue' => 'Opelucid City Gym',
            'reward' => 'Legend Badge',
            'sprite' => 'drayden.gif',
            'badge' => 'legend.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 51,
            'roster' => ['Druddigon', 'Flygon', 'Altaria', 'Haxorus'],
        ],
        45 => [
            'route' => 'Marlon',
            'display' => 'Marlon',
            'venue' => 'Humilau City Gym',
            'reward' => 'Wave Badge',
            'sprite' => 'marlon.gif',
            'badge' => 'wave.gif',
            'division' => 'Gym Leader',
            'region' => 'Unova',
            'level' => 57,
            'roster' => ['Wailord', 'Carracosta', 'Mantine', 'Jellicent'],
        ],
        46 => [
            'route' => 'Will',
            'display' => 'Will',
            'venue' => 'Indigo Elite Four #1',
            'reward' => 'Will\'s Elite Badge',
            'sprite' => 'will.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Indigo',
            'level' => 58,
            'roster' => ['Slowbro', 'Girafarig', 'Exeggutor', 'Jynx', 'Xatu', 'Slowking'],
        ],
        47 => [
            'route' => 'Koga',
            'display' => 'Koga',
            'venue' => 'Indigo Elite Four #2',
            'reward' => 'Koga\'s Elite Badge',
            'sprite' => 'koga.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Indigo',
            'level' => 60,
            'roster' => ['Arbok', 'Ariados', 'Venomoth', 'Forretress', 'Crobat', 'Weezing'],
        ],
        48 => [
            'route' => 'Bruno',
            'display' => 'Bruno',
            'venue' => 'Indigo Elite Four #3',
            'reward' => 'Bruno\'s Elite Badge',
            'sprite' => 'bruno.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Indigo',
            'level' => 62,
            'roster' => ['Hitmontop', 'Onix', 'Steelix', 'Hitmonlee', 'Hitmonchan', 'Machamp'],
        ],
        49 => [
            'route' => 'Karen',
            'display' => 'Karen',
            'venue' => 'Indigo Elite Four #4',
            'reward' => 'Karen\'s Elite Badge',
            'sprite' => 'karen.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Indigo',
            'level' => 64,
            'roster' => ['Umbreon', 'Victreebel', 'Misdreavus', 'Murkrow', 'Vileplume', 'Gengar'],
        ],
        50 => [
            'route' => 'Sidney',
            'display' => 'Sidney',
            'venue' => 'Hoenn Elite Four #1',
            'reward' => 'Sidney\'s Elite Badge',
            'sprite' => 'sidney.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Hoenn',
            'level' => 55,
            'roster' => ['Mightyena', 'Shiftry', 'Cacturne', 'Sharpedo', 'Crawdaunt', 'Absol'],
        ],
        51 => [
            'route' => 'Phoebe',
            'display' => 'Phoebe',
            'venue' => 'Hoenn Elite Four #2',
            'reward' => 'Phoebe\'s Elite Badge',
            'sprite' => 'phoebe.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Hoenn',
            'level' => 57,
            'roster' => ['Dusclops', 'Banette', 'Sableye', 'Banette', 'Dusclops', 'Gengar'],
        ],
        52 => [
            'route' => 'Glacia',
            'display' => 'Glacia',
            'venue' => 'Hoenn Elite Four #3',
            'reward' => 'Glacia\'s Elite Badge',
            'sprite' => 'glacia.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Hoenn',
            'level' => 59,
            'roster' => ['Glalie', 'Sealeo', 'Lapras', 'Sealeo', 'Glalie', 'Walrein'],
        ],
        53 => [
            'route' => 'Drake',
            'display' => 'Drake',
            'venue' => 'Hoenn Elite Four #4',
            'reward' => 'Drake\'s Elite Badge',
            'sprite' => 'drake.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Hoenn',
            'level' => 61,
            'roster' => ['Shelgon', 'Altaria', 'Flygon', 'Kingdra', 'Flygon', 'Salamence'],
        ],
        54 => [
            'route' => 'Aaron',
            'display' => 'Aaron',
            'venue' => 'Sinnoh Elite Four #1',
            'reward' => 'Aaron\'s Elite Badge',
            'sprite' => 'aaron.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Sinnoh',
            'level' => 62,
            'roster' => ['Drapion', 'Yanmega', 'Scizor', 'Heracross', 'Vespiquen', 'Drapion'],
        ],
        55 => [
            'route' => 'Bertha',
            'display' => 'Bertha',
            'venue' => 'Sinnoh Elite Four #2',
            'reward' => 'Bertha\'s Elite Badge',
            'sprite' => 'bertha.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Sinnoh',
            'level' => 64,
            'roster' => ['Hippowdon', 'Whiscash', 'Gliscor', 'Golem', 'Rhydon', 'Rhyperior'],
        ],
        56 => [
            'route' => 'Flint',
            'display' => 'Flint',
            'venue' => 'Sinnoh Elite Four #3',
            'reward' => 'Flint\'s Elite Badge',
            'sprite' => 'flint.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Sinnoh',
            'level' => 66,
            'roster' => ['Magmar', 'Houndoom', 'Flareon', 'Rapidash', 'Infernape', 'Magmortar'],
        ],
        57 => [
            'route' => 'Lucian',
            'display' => 'Lucian',
            'venue' => 'Sinnoh Elite Four #4',
            'reward' => 'Lucian\'s Elite Badge',
            'sprite' => 'lucian.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Sinnoh',
            'level' => 68,
            'roster' => ['Girafarig', 'Mr. Mime', 'Espeon', 'Bronzong', 'Alakazam', 'Gallade'],
        ],
        58 => [
            'route' => 'Shauntal',
            'display' => 'Shauntal',
            'venue' => 'Unova Elite Four #1',
            'reward' => 'Shauntal\'s Elite Badge',
            'sprite' => 'shauntal.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Unova',
            'level' => 62,
            'roster' => ['Cofagrigus', 'Drifblim', 'Jellicent', 'Golurk', 'Banette', 'Chandelure'],
        ],
        59 => [
            'route' => 'Grimsley',
            'display' => 'Grimsley',
            'venue' => 'Unova Elite Four #3',
            'reward' => 'Grimsley\'s Elite Badge',
            'sprite' => 'grimsley.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Unova',
            'level' => 66,
            'roster' => ['Liepard', 'Umbreon', 'Scrafty', 'Krookodile', 'Absol', 'Bisharp'],
        ],
        60 => [
            'route' => 'Caitlin',
            'display' => 'Caitlin',
            'venue' => 'Unova Elite Four #4',
            'reward' => 'Caitlin\'s Elite Badge',
            'sprite' => 'caitlin.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Unova',
            'level' => 68,
            'roster' => ['Musharna', 'Grumpig', 'Reuniclus', 'Sigilyph', 'Gothitelle', 'Metagross'],
        ],
        61 => [
            'route' => 'Marshal',
            'display' => 'Marshal',
            'venue' => 'Unova Elite Four #2',
            'reward' => 'Marshal\'s Elite Badge',
            'sprite' => 'marshal.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Unova',
            'level' => 64,
            'roster' => ['Throh', 'Sawk', 'Hariyama', 'Mienshao', 'Lucario', 'Conkeldurr'],
        ],
        62 => [
            'route' => 'Blue',
            'display' => 'Blue',
            'venue' => 'Kanto Champion',
            'reward' => 'Kanto League Champion',
            'sprite' => 'blue.gif',
            'badge' => '',
            'division' => 'Champion',
            'region' => 'Kanto',
            'level' => 68,
            'roster' => ['Pidgeot', 'Alakazam', 'Rhydon', 'Gyarados', 'Arcanine', 'Venusaur'],
        ],
        63 => [
            'route' => 'Lance',
            'display' => 'Lance',
            'venue' => 'Johto Champion',
            'reward' => 'Johto League Champion',
            'sprite' => 'lance.gif',
            'badge' => '',
            'division' => 'Champion',
            'region' => 'Johto',
            'level' => 68,
            'roster' => ['Gyarados', 'Dragonite', 'Aerodactyl', 'Dragonite', 'Charizard', 'Dragonite'],
        ],
        64 => [
            'route' => 'Juan',
            'display' => 'Juan',
            'venue' => 'Sootopolis City Gym',
            'reward' => 'Rain Badge',
            'sprite' => 'juan.gif',
            'badge' => 'rain.gif',
            'division' => 'Gym Leader',
            'region' => 'Hoenn',
            'level' => 50,
            'roster' => ['Kingdra', 'Whiscash', 'Relicanth', 'Walrein', 'Crawdaunt', 'Politoed'],
        ],
        65 => [
            'route' => 'Cynthia',
            'display' => 'Cynthia',
            'venue' => 'Sinnoh Champion',
            'reward' => 'Sinnoh League Champion',
            'sprite' => 'cynthia.gif',
            'badge' => '',
            'division' => 'Champion',
            'region' => 'Sinnoh',
            'level' => 72,
            'roster' => ['Spiritomb', 'Roserade', 'Milotic', 'Lucario', 'Togekiss', 'Garchomp'],
        ],
        66 => [
            'route' => 'Iris',
            'display' => 'Iris',
            'venue' => 'Unova Champion',
            'reward' => 'Unova League Champion',
            'sprite' => 'iris.gif',
            'badge' => '',
            'division' => 'Champion',
            'region' => 'Unova',
            'level' => 72,
            'roster' => ['Hydreigon', 'Druddigon', 'Archeops', 'Aggron', 'Lapras', 'Haxorus'],
        ],
        67 => [
            'route' => 'Salon Maiden Anabel',
            'display' => 'Salon Maiden Anabel',
            'venue' => 'Battle Tower',
            'reward' => 'Ability Symbol',
            'sprite' => 'anabel.gif',
            'badge' => 'ability symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 110,
            'roster' => ['Alakazam', 'Entei', 'Snorlax'],
        ],
        68 => [
            'route' => 'Palace Mavern Spenser',
            'display' => 'Palace Mavern Spenser',
            'venue' => 'Battle Palace',
            'reward' => 'Spirit Symbol',
            'sprite' => 'spenser.gif',
            'badge' => 'spirit symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 112,
            'roster' => ['Crobat', 'Slaking', 'Lapras'],
        ],
        69 => [
            'route' => 'Factory Head Noland',
            'display' => 'Factory Head Noland',
            'venue' => 'Battle Factory',
            'reward' => 'Knowledge Symbol',
            'sprite' => 'noland.gif',
            'badge' => 'knowledge symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 114,
            'roster' => ['Blaziken', 'Swampert', 'Sceptile'],
        ],
        70 => [
            'route' => 'Pyramid King Brandon',
            'display' => 'Pyramid King Brandon',
            'venue' => 'Battle Pyramid',
            'reward' => 'Brave Symbol',
            'sprite' => 'brandon.gif',
            'badge' => 'brave symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 116,
            'roster' => ['Regirock', 'Regice', 'Registeel'],
        ],
        71 => [
            'route' => 'Dome Ace Tucker',
            'display' => 'Dome Ace Tucker',
            'venue' => 'Battle Dome',
            'reward' => 'Tactics Symbol',
            'sprite' => 'tucker.gif',
            'badge' => 'tactics symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 118,
            'roster' => ['Swampert', 'Charizard', 'Metagross'],
        ],
        72 => [
            'route' => 'Arena Tycoon Greta',
            'display' => 'Arena Tycoon Greta',
            'venue' => 'Battle Arena',
            'reward' => 'Guts Symbol',
            'sprite' => 'greta.gif',
            'badge' => 'guts symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 120,
            'roster' => ['Heracross', 'Umbreon', 'Shedinja'],
        ],
        73 => [
            'route' => 'Pike Queen Lucy',
            'display' => 'Pike Queen Lucy',
            'venue' => 'Battle Pike',
            'reward' => 'Luck Symbol',
            'sprite' => 'lucy.gif',
            'badge' => 'luck symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Hoenn',
            'level' => 122,
            'roster' => ['Seviper', 'Milotic', 'Shuckle'],
        ],
        74 => [
            'route' => 'Tower Tycoon Palmer',
            'display' => 'Tower Tycoon Palmer',
            'venue' => 'Battle Tower',
            'reward' => 'Palmer Symbol',
            'sprite' => 'palmer.gif',
            'badge' => 'palmer symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Sinnoh',
            'level' => 125,
            'roster' => ['Dragonite', 'Rhyperior', 'Milotic'],
        ],
        75 => [
            'route' => 'Factory Head Thorton',
            'display' => 'Factory Head Thorton',
            'venue' => 'Battle Factory',
            'reward' => 'Thorton Symbol',
            'sprite' => 'thorton.gif',
            'badge' => 'thorton symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Sinnoh',
            'level' => 128,
            'roster' => ['Magmortar', 'Electivire', 'Rhyperior'],
        ],
        76 => [
            'route' => 'Arcade Star Dahlia',
            'display' => 'Arcade Star Dahlia',
            'venue' => 'Battle Arcade',
            'reward' => 'Dahlia Symbol',
            'sprite' => 'dahlia.gif',
            'badge' => 'dahlia symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Sinnoh',
            'level' => 131,
            'roster' => ['Dusknoir', 'Medicham', 'Ludicolo'],
        ],
        77 => [
            'route' => 'Castle Valet Darach',
            'display' => 'Castle Valet Darach',
            'venue' => 'Battle Castle',
            'reward' => 'Darach Symbol',
            'sprite' => 'darach.gif',
            'badge' => 'darach symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Sinnoh',
            'level' => 134,
            'roster' => ['Staraptor', 'Empoleon', 'Houndoom'],
        ],
        78 => [
            'route' => 'Hall Matron Argenta',
            'display' => 'Hall Matron Argenta',
            'venue' => 'Battle Hall',
            'reward' => 'Argenta Symbol',
            'sprite' => 'argenta.gif',
            'badge' => 'argenta symbol.gif',
            'division' => 'Frontier Brain',
            'region' => 'Sinnoh',
            'level' => 137,
            'roster' => ['Togekiss', 'Milotic', 'Garchomp'],
        ],
        79 => [
            'route' => 'Viola',
            'display' => 'Viola',
            'venue' => 'Santalune City Gym',
            'reward' => 'Bug Badge',
            'sprite' => 'viola.gif',
            'badge' => 'bug.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 15,
            'roster' => ['Surskit', 'Vivillon (Meadow)'],
        ],
        80 => [
            'route' => 'Grant',
            'display' => 'Grant',
            'venue' => 'Cyllage City Gym',
            'reward' => 'Cliff Badge',
            'sprite' => 'grant.gif',
            'badge' => 'cliff.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 21,
            'roster' => ['Tyrunt', 'Amaura'],
        ],
        81 => [
            'route' => 'Korrina',
            'display' => 'Korrina',
            'venue' => 'Shalour City Gym',
            'reward' => 'Rumble Badge',
            'sprite' => 'korrina.gif',
            'badge' => 'rumble.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 27,
            'roster' => ['Mienfoo', 'Hawlucha', 'Machoke'],
        ],
        82 => [
            'route' => 'Ramos',
            'display' => 'Ramos',
            'venue' => 'Coumarine City Gym',
            'reward' => 'Plant Badge',
            'sprite' => 'ramos.gif',
            'badge' => 'plant.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 33,
            'roster' => ['Jumpluff', 'Gogoat', 'Weepinbell'],
        ],
        83 => [
            'route' => 'Clemont',
            'display' => 'Clemont',
            'venue' => 'Lumiose City Gym',
            'reward' => 'Voltage Badge',
            'sprite' => 'clemont.gif',
            'badge' => 'voltage.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 39,
            'roster' => ['Emolga', 'Magneton', 'Heliolisk'],
        ],
        84 => [
            'route' => 'Valerie',
            'display' => 'Valerie',
            'venue' => 'Laverre City Gym',
            'reward' => 'Fairy Badge',
            'sprite' => 'valerie.gif',
            'badge' => 'fairy.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 45,
            'roster' => ['Mawile', 'Mr. Mime', 'Sylveon'],
        ],
        85 => [
            'route' => 'Olympia',
            'display' => 'Olympia',
            'venue' => 'Anistar City Gym',
            'reward' => 'Psychic Badge',
            'sprite' => 'olympia.gif',
            'badge' => 'psychic.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 51,
            'roster' => ['Sigilyph', 'Slowking', 'Meowstic (F)'],
        ],
        86 => [
            'route' => 'Wulfric',
            'display' => 'Wulfric',
            'venue' => 'Snowbelle City Gym',
            'reward' => 'Iceberg Badge',
            'sprite' => 'wulfric.gif',
            'badge' => 'iceberg.gif',
            'division' => 'Gym Leader',
            'region' => 'Kalos',
            'level' => 57,
            'roster' => ['Abomasnow', 'Cryogonal', 'Avalugg'],
        ],
        87 => [
            'route' => 'Malva',
            'display' => 'Malva',
            'venue' => 'Kalos Elite Four #2',
            'reward' => 'Malva\'s Elite Badge',
            'sprite' => 'malva.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Kalos',
            'level' => 64,
            'roster' => ['Pyroar', 'Torkoal', 'Chandelure', 'Talonflame'],
        ],
        88 => [
            'route' => 'Wikstrom',
            'display' => 'Wikstrom',
            'venue' => 'Kalos Elite Four #1',
            'reward' => 'Wikstrom\'s Elite Badge',
            'sprite' => 'wikstrom.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Kalos',
            'level' => 62,
            'roster' => ['Klefki', 'Probopass', 'Scizor', 'Aegislash (Blade)'],
        ],
        89 => [
            'route' => 'Drasna',
            'display' => 'Drasna',
            'venue' => 'Kalos Elite Four #3',
            'reward' => 'Drasna\'s Elite Badge',
            'sprite' => 'drasna.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Kalos',
            'level' => 66,
            'roster' => ['Dragalge', 'Altaria', 'Druddigon', 'Noivern'],
        ],
        90 => [
            'route' => 'Siebold',
            'display' => 'Siebold',
            'venue' => 'Kalos Elite Four #4',
            'reward' => 'Siebold\'s Elite Badge',
            'sprite' => 'siebold.gif',
            'badge' => '',
            'division' => 'Elite Four',
            'region' => 'Kalos',
            'level' => 68,
            'roster' => ['Clawitzer', 'Starmie', 'Gyarados', 'Barbaracle'],
        ],
        91 => [
            'route' => 'Diantha',
            'display' => 'Diantha',
            'venue' => 'Kalos Champion',
            'reward' => 'Kalos League Champion',
            'sprite' => 'diantha.gif',
            'badge' => '',
            'division' => 'Champion',
            'region' => 'Kalos',
            'level' => 72,
            'roster' => ['Hawlucha', 'Tyrantrum', 'Aurorus', 'Gourgeist (Average)', 'Goodra', 'Gardevoir (Mega)'],
        ],
        92 => [
            'route' => 'Battle Chatelaine Nita',
            'display' => 'Nita',
            'venue' => 'Battle Maison',
            'reward' => 'Nita Symbol',
            'sprite' => 'nita.gif',
            'badge' => '',
            'division' => 'Battle Chatelaine',
            'region' => 'Kalos',
            'level' => 140,
            'roster' => ['Grumpig', 'Wigglytuff', 'Purugly'],
        ],
        93 => [
            'route' => 'Battle Chatelaine Evelyn',
            'display' => 'Evelyn',
            'venue' => 'Battle Maison',
            'reward' => 'Evelyn Symbol',
            'sprite' => 'evelyn.gif',
            'badge' => '',
            'division' => 'Battle Chatelaine',
            'region' => 'Kalos',
            'level' => 145,
            'roster' => ['Persian', 'Lumineon', 'Pachirisu', 'Primeape'],
        ],
        94 => [
            'route' => 'Battle Chatelaine Dana',
            'display' => 'Dana',
            'venue' => 'Battle Maison',
            'reward' => 'Dana Symbol',
            'sprite' => 'dana.gif',
            'badge' => '',
            'division' => 'Battle Chatelaine',
            'region' => 'Kalos',
            'level' => 150,
            'roster' => ['Magneton', 'Piloswine', 'Girafarig', 'Wobbuffet', 'Magmar', 'Porygon2'],
        ],
        95 => [
            'route' => 'Battle Chatelaine Morgan',
            'display' => 'Morgan',
            'venue' => 'Battle Maison',
            'reward' => 'Morgan Symbol',
            'sprite' => 'morgan.gif',
            'badge' => '',
            'division' => 'Battle Chatelaine',
            'region' => 'Kalos',
            'level' => 155,
            'roster' => ['Klefki', 'Beheeyem', 'Swalot', 'Marowak', 'Mandibuzz', 'Sawsbuck (Spring)'],
        ],
    ];
    return $catalog;
}

function pv_battle_groups(): array
{
    return [
        'league' => [
            'kanto' => ['label' => 'Kanto League', 'subtitle' => 'Eight Kanto gyms, the shared Indigo Elite Four and Champion Blue.', 'ids' => [1, 2, 3, 4, 5, 6, 7, 8, 46, 47, 48, 49, 62]],
            'orangeislands' => ['label' => 'Orange League', 'subtitle' => 'Orange Crew challenges culminating at Pummelo Stadium.', 'ids' => [9, 10, 11, 12, 13]],
            'johto' => ['label' => 'Johto League', 'subtitle' => 'Eight Johto gyms, the Indigo Elite Four and Champion Lance.', 'ids' => [14, 15, 16, 17, 18, 19, 20, 21, 46, 47, 48, 49, 63]],
            'hoenn' => ['label' => 'Hoenn League', 'subtitle' => 'Eight Hoenn gyms, Elite Four and Champion Wallace.', 'ids' => [22, 23, 24, 25, 26, 27, 28, 64, 50, 51, 52, 53, 29]],
            'sinnoh' => ['label' => 'Sinnoh League', 'subtitle' => 'Eight Sinnoh gyms, Elite Four and Champion Cynthia.', 'ids' => [30, 31, 32, 33, 34, 35, 36, 37, 54, 55, 56, 57, 65]],
            'unova' => ['label' => 'Unova League', 'subtitle' => 'Eight Unova gyms, Elite Four and Champion Iris.', 'ids' => [38, 39, 40, 41, 42, 43, 44, 45, 58, 61, 59, 60, 66]],
            'kalos' => ['label' => 'Kalos League', 'subtitle' => 'Eight Kalos gyms, Elite Four and Champion Diantha.', 'ids' => [79, 80, 81, 82, 83, 84, 85, 86, 88, 87, 89, 90, 91]],
        ],
        'facility' => [
            'hoenn' => ['label' => 'Hoenn Battle Frontier', 'subtitle' => 'Seven Frontier Brain battles above the normal league level cap.', 'ids' => [67, 68, 69, 70, 71, 72, 73]],
            'sinnoh' => ['label' => 'Sinnoh Battle Frontier', 'subtitle' => 'Five elite Sinnoh facility bosses await endgame challengers.', 'ids' => [74, 75, 76, 77, 78]],
            'kalos' => ['label' => 'Kalos Battle Maison', 'subtitle' => 'Four Battle Chatelaines form the final facility ladder.', 'ids' => [92, 93, 94, 95]],
        ],
    ];
}

function pv_battle_species_data(): array
{
    static $species = null;
    if ($species !== null) return $species;
    $species = [
        'Abomasnow' => ['type1' => 'Grass', 'type2' => 'Ice', 'moves' => ['Ice Punch', 'Icy Wind', 'Leer', 'Powder Snow']],
        'Absol' => ['type1' => 'Dark', 'type2' => '', 'moves' => ['Feint', 'Future Sight', 'Leer', 'Perish Song']],
        'Aegislash (Blade)' => ['type1' => 'Steel', 'type2' => 'Ghost', 'moves' => ['Aerial Ace', 'Autotomize', 'Fury Cutter', 'Head Smash']],
        'Aerodactyl' => ['type1' => 'Rock', 'type2' => 'Flying', 'moves' => ['Bite', 'Fire Fang', 'Ice Fang', 'Iron Head']],
        'Aggron' => ['type1' => 'Steel', 'type2' => 'Rock', 'moves' => ['Harden', 'Headbutt', 'Mud-Slap', 'Tackle']],
        'Alakazam' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Confusion', 'Kinesis', 'Teleport', 'Confusion']],
        'Altaria' => ['type1' => 'Dragon', 'type2' => 'Flying', 'moves' => ['Astonish', 'Dragon Breath', 'Growl', 'Peck']],
        'Amaura' => ['type1' => 'Rock', 'type2' => 'Ice', 'moves' => ['Growl', 'Powder Snow', 'Thunder Wave', 'Rock Throw']],
        'Ambipom' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Double Hit', 'Astonish', 'Dual Chop', 'Sand Attack']],
        'Arbok' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Bite', 'Crunch', 'Fire Fang', 'Ice Fang']],
        'Arcanine' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Bite', 'Fire Fang', 'Odor Sleuth', 'Roar']],
        'Archeops' => ['type1' => 'Rock', 'type2' => 'Flying', 'moves' => ['Leer', 'Quick Attack', 'Rock Throw', 'Wing Attack']],
        'Ariados' => ['type1' => 'Bug', 'type2' => 'Poison', 'moves' => ['Absorb', 'Bug Bite', 'Constrict', 'Fell Stinger']],
        'Aurorus' => ['type1' => 'Rock', 'type2' => 'Ice', 'moves' => ['Freeze-Dry', 'Growl', 'Powder Snow', 'Rock Throw']],
        'Avalugg' => ['type1' => 'Ice', 'type2' => '', 'moves' => ['Bite', 'Body Slam', 'Crunch', 'Harden']],
        'Banette' => ['type1' => 'Ghost', 'type2' => '', 'moves' => ['Knock Off', 'Night Shade', 'Phantom Force', 'Screech']],
        'Barbaracle' => ['type1' => 'Rock', 'type2' => 'Water', 'moves' => ['Sand Attack', 'Scratch', 'Shell Smash', 'Skull Bash']],
        'Bastiodon' => ['type1' => 'Rock', 'type2' => 'Steel', 'moves' => ['Block', 'Metal Sound', 'Protect', 'Tackle']],
        'Beheeyem' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Confusion', 'Growl', 'Heal Block', 'Miracle Eye']],
        'Bisharp' => ['type1' => 'Dark', 'type2' => 'Steel', 'moves' => ['Fury Cutter', 'Guillotine', 'Iron Head', 'Leer']],
        'Blastoise' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Flash Cannon', 'Tackle', 'Tail Whip', 'Water Gun']],
        'Blaziken' => ['type1' => 'Fire', 'type2' => 'Fighting', 'moves' => ['Blaze Kick', 'Double Kick', 'Ember', 'Fire Punch']],
        'Bronzong' => ['type1' => 'Steel', 'type2' => 'Psychic', 'moves' => ['Block', 'Confusion', 'Hypnosis', 'Imprison']],
        'Bronzor' => ['type1' => 'Steel', 'type2' => 'Psychic', 'moves' => ['Confusion', 'Tackle', 'Hypnosis', 'Imprison']],
        'Cacturne' => ['type1' => 'Grass', 'type2' => 'Dark', 'moves' => ['Absorb', 'Destiny Bond', 'Growth', 'Leer']],
        'Camerupt' => ['type1' => 'Fire', 'type2' => 'Ground', 'moves' => ['Ember', 'Eruption', 'Fissure', 'Focus Energy']],
        'Carracosta' => ['type1' => 'Water', 'type2' => 'Rock', 'moves' => ['Bide', 'Rollout', 'Water Gun', 'Withdraw']],
        'Chandelure' => ['type1' => 'Ghost', 'type2' => 'Fire', 'moves' => ['Confuse Ray', 'Flame Burst', 'Hex', 'Pain Split']],
        'Charizard' => ['type1' => 'Fire', 'type2' => 'Flying', 'moves' => ['Air Slash', 'Dragon Claw', 'Ember', 'Flare Blitz']],
        'Charmeleon' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Ember', 'Growl', 'Scratch', 'Ember']],
        'Cherubi' => ['type1' => 'Grass', 'type2' => '', 'moves' => ['Morning Sun', 'Tackle', 'Growth', 'Leech Seed']],
        'Clawitzer' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Aura Sphere', 'Dark Pulse', 'Dragon Pulse', 'Heal Pulse']],
        'Claydol' => ['type1' => 'Ground', 'type2' => 'Psychic', 'moves' => ['Confusion', 'Harden', 'Hyper Beam', 'Rapid Spin']],
        'Clefairy' => ['type1' => 'Fairy', 'type2' => 'Normal', 'moves' => ['Disarming Voice', 'Encore', 'Growl', 'Pound']],
        'Cofagrigus' => ['type1' => 'Ghost', 'type2' => '', 'moves' => ['Astonish', 'Disable', 'Haze', 'Protect']],
        'Conkeldurr' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Bide', 'Focus Energy', 'Leer', 'Pound']],
        'Cranidos' => ['type1' => 'Rock', 'type2' => '', 'moves' => ['Headbutt', 'Leer', 'Focus Energy', 'Pursuit']],
        'Crawdaunt' => ['type1' => 'Water', 'type2' => 'Dark', 'moves' => ['Bubble', 'Harden', 'Leer', 'Swift']],
        'Crobat' => ['type1' => 'Poison', 'type2' => 'Flying', 'moves' => ['Absorb', 'Astonish', 'Bite', 'Cross Poison']],
        'Cryogonal' => ['type1' => 'Ice', 'type2' => '', 'moves' => ['Bind', 'Ice Shard', 'Night Slash', 'Rapid Spin']],
        'Dewgong' => ['type1' => 'Water', 'type2' => 'Ice', 'moves' => ['Growl', 'Headbutt', 'Icy Wind', 'Sheer Cold']],
        'Ditto' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Transform', 'Tackle', 'Copycat', 'Struggle']],
        'Dragalge' => ['type1' => 'Poison', 'type2' => 'Dragon', 'moves' => ['Dragon Tail', 'Feint Attack', 'Smokescreen', 'Tackle']],
        'Dragonair' => ['type1' => 'Dragon', 'type2' => '', 'moves' => ['Leer', 'Thunder Wave', 'Twister', 'Wrap']],
        'Dragonite' => ['type1' => 'Dragon', 'type2' => 'Flying', 'moves' => ['Fire Punch', 'Hurricane', 'Leer', 'Roost']],
        'Drapion' => ['type1' => 'Poison', 'type2' => 'Dark', 'moves' => ['Bite', 'Fire Fang', 'Ice Fang', 'Knock Off']],
        'Dratini' => ['type1' => 'Dragon', 'type2' => '', 'moves' => ['Leer', 'Wrap', 'Thunder Wave', 'Twister']],
        'Drifblim' => ['type1' => 'Ghost', 'type2' => 'Flying', 'moves' => ['Astonish', 'Constrict', 'Gust', 'Minimize']],
        'Druddigon' => ['type1' => 'Dragon', 'type2' => '', 'moves' => ['Leer', 'Scratch', 'Hone Claws', 'Bite']],
        'Dugtrio' => ['type1' => 'Ground', 'type2' => '', 'moves' => ['Growl', 'Night Slash', 'Rototiller', 'Sand Attack']],
        'Dusclops' => ['type1' => 'Ghost', 'type2' => '', 'moves' => ['Astonish', 'Bind', 'Disable', 'Fire Punch']],
        'Dusknoir' => ['type1' => 'Ghost', 'type2' => '', 'moves' => ['Astonish', 'Bind', 'Disable', 'Fire Punch']],
        'Dwebble' => ['type1' => 'Bug', 'type2' => 'Rock', 'moves' => ['Fury Cutter', 'Rock Blast', 'Withdraw', 'Sand Attack']],
        'Electabuzz' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Leer', 'Quick Attack', 'Thunder Shock', 'Thunder Shock']],
        'Electivire' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Electric Terrain', 'Fire Punch', 'Ion Deluge', 'Leer']],
        'Electrode' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Charge', 'Eerie Impulse', 'Magnetic Flux', 'Sonic Boom']],
        'Emolga' => ['type1' => 'Electric', 'type2' => 'Flying', 'moves' => ['Thunder Shock', 'Quick Attack', 'Tail Whip', 'Charge']],
        'Empoleon' => ['type1' => 'Water', 'type2' => 'Steel', 'moves' => ['Aqua Jet', 'Bubble', 'Growl', 'Metal Claw']],
        'Entei' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Bite', 'Eruption', 'Extrasensory', 'Lava Plume']],
        'Espeon' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Confusion', 'Helping Hand', 'Tackle', 'Tail Whip']],
        'Excadrill' => ['type1' => 'Ground', 'type2' => 'Steel', 'moves' => ['Horn Drill', 'Mud-Slap', 'Mud Sport', 'Rapid Spin']],
        'Exeggutor' => ['type1' => 'Grass', 'type2' => 'Psychic', 'moves' => ['Barrage', 'Confusion', 'Hypnosis', 'Seed Bomb']],
        'Flaaffy' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Growl', 'Tackle', 'Thunder Shock', 'Thunder Wave']],
        'Flareon' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Ember', 'Helping Hand', 'Tackle', 'Tail Whip']],
        'Floatzel' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Crunch', 'Growl', 'Ice Fang', 'Quick Attack']],
        'Flygon' => ['type1' => 'Ground', 'type2' => 'Dragon', 'moves' => ['Bide', 'Dragon Breath', 'Dragon Claw', 'Dragon Dance']],
        'Forretress' => ['type1' => 'Bug', 'type2' => 'Steel', 'moves' => ['Autotomize', 'Bug Bite', 'Heavy Slam', 'Magnet Rise']],
        'Gallade' => ['type1' => 'Psychic', 'type2' => 'Fighting', 'moves' => ['Close Combat', 'Confusion', 'Double Team', 'Leaf Blade']],
        'Garchomp' => ['type1' => 'Dragon', 'type2' => 'Ground', 'moves' => ['Crunch', 'Dragon Rage', 'Dual Chop', 'Fire Fang']],
        'Gardevoir (Mega)' => ['type1' => 'Psychic', 'type2' => 'Fairy', 'moves' => ['Confusion', 'Double Team', 'Growl', 'Healing Wish']],
        'Gastly' => ['type1' => 'Ghost', 'type2' => 'Poison', 'moves' => ['Hypnosis', 'Lick', 'Spite', 'Mean Look']],
        'Gengar' => ['type1' => 'Ghost', 'type2' => 'Poison', 'moves' => ['Hypnosis', 'Lick', 'Shadow Punch', 'Spite']],
        'Geodude' => ['type1' => 'Rock', 'type2' => 'Ground', 'moves' => ['Defense Curl', 'Tackle', 'Mud Sport', 'Rock Polish']],
        'Girafarig' => ['type1' => 'Normal', 'type2' => 'Psychic', 'moves' => ['Astonish', 'Confusion', 'Growl', 'Guard Swap']],
        'Glalie' => ['type1' => 'Ice', 'type2' => '', 'moves' => ['Double Team', 'Freeze-Dry', 'Ice Shard', 'Leer']],
        'Gliscor' => ['type1' => 'Ground', 'type2' => 'Flying', 'moves' => ['Fire Fang', 'Guillotine', 'Harden', 'Ice Fang']],
        'Gogoat' => ['type1' => 'Grass', 'type2' => '', 'moves' => ['Aerial Ace', 'Earthquake', 'Growth', 'Tackle']],
        'Golem' => ['type1' => 'Rock', 'type2' => 'Ground', 'moves' => ['Defense Curl', 'Heavy Slam', 'Mud Sport', 'Rock Polish']],
        'Golurk' => ['type1' => 'Ground', 'type2' => 'Ghost', 'moves' => ['Astonish', 'Defense Curl', 'Heavy Slam', 'High Horsepower']],
        'Goodra' => ['type1' => 'Dragon', 'type2' => '', 'moves' => ['Absorb', 'Aqua Tail', 'Bubble', 'Feint']],
        'Gothitelle' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Confusion', 'Play Nice', 'Pound', 'Tickle']],
        'Gourgeist (Average)' => ['type1' => 'Ghost', 'type2' => 'Grass', 'moves' => ['Astonish', 'Confuse Ray', 'Explosion', 'Phantom Force']],
        'Grimer' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Poison Gas', 'Pound', 'Harden', 'Mud-Slap']],
        'Growlithe' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Bite', 'Roar', 'Ember', 'Leer']],
        'Grumpig' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Belch', 'Odor Sleuth', 'Psybeam', 'Psywave']],
        'Gyarados' => ['type1' => 'Water', 'type2' => 'Flying', 'moves' => ['Bite', 'Thrash', 'Leer', 'Twister']],
        'Hariyama' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Arm Thrust', 'Brine', 'Focus Energy', 'Sand Attack']],
        'Haunter' => ['type1' => 'Ghost', 'type2' => 'Poison', 'moves' => ['Hypnosis', 'Lick', 'Shadow Punch', 'Spite']],
        'Hawlucha' => ['type1' => 'Fighting', 'type2' => 'Flying', 'moves' => ['Detect', 'Hone Claws', 'Tackle', 'Karate Chop']],
        'Haxorus' => ['type1' => 'Dragon', 'type2' => '', 'moves' => ['Assurance', 'Dragon Rage', 'Leer', 'Outrage']],
        'Heliolisk' => ['type1' => 'Electric', 'type2' => 'Normal', 'moves' => ['Charge', 'Eerie Impulse', 'Electrify', 'Parabolic Charge']],
        'Heracross' => ['type1' => 'Bug', 'type2' => 'Fighting', 'moves' => ['Arm Thrust', 'Bullet Seed', 'Endure', 'Horn Attack']],
        'Hippowdon' => ['type1' => 'Ground', 'type2' => '', 'moves' => ['Bite', 'Fire Fang', 'Ice Fang', 'Sand Attack']],
        'Hitmonchan' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Agility', 'Close Combat', 'Comet Punch', 'Counter']],
        'Hitmonlee' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Close Combat', 'Double Kick', 'Jump Kick', 'Meditate']],
        'Hitmontop' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Close Combat', 'Detect', 'Endeavor', 'Focus Energy']],
        'Houndoom' => ['type1' => 'Dark', 'type2' => 'Fire', 'moves' => ['Ember', 'Howl', 'Inferno', 'Leer']],
        'Hydreigon' => ['type1' => 'Dark', 'type2' => 'Dragon', 'moves' => ['Bite', 'Dragon Rage', 'Focus Energy', 'Hyper Voice']],
        'Infernape' => ['type1' => 'Fire', 'type2' => 'Fighting', 'moves' => ['Close Combat', 'Ember', 'Flare Blitz', 'Leer']],
        'Jellicent' => ['type1' => 'Water', 'type2' => 'Ghost', 'moves' => ['Absorb', 'Bubble', 'Night Shade', 'Water Sport']],
        'Jigglypuff' => ['type1' => 'Normal', 'type2' => 'Fairy', 'moves' => ['Sing', 'Defense Curl', 'Pound', 'Play Nice']],
        'Joltik' => ['type1' => 'Bug', 'type2' => 'Electric', 'moves' => ['Absorb', 'Spider Web', 'String Shot', 'Thunder Wave']],
        'Jumpluff' => ['type1' => 'Grass', 'type2' => 'Flying', 'moves' => ['Splash', 'Synthesis', 'Tackle', 'Tail Whip']],
        'Jynx' => ['type1' => 'Ice', 'type2' => 'Psychic', 'moves' => ['Draining Kiss', 'Lick', 'Lovely Kiss', 'Perish Song']],
        'Kadabra' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Confusion', 'Kinesis', 'Teleport', 'Confusion']],
        'Kakuna' => ['type1' => 'Bug', 'type2' => 'Poison', 'moves' => ['Harden', 'Harden', 'Harden', 'Harden']],
        'Karrablast' => ['type1' => 'Bug', 'type2' => '', 'moves' => ['Peck', 'Leer', 'Endure', 'Fury Cutter']],
        'Kingdra' => ['type1' => 'Water', 'type2' => 'Dragon', 'moves' => ['Bubble', 'Hydro Pump', 'Leer', 'Smokescreen']],
        'Klefki' => ['type1' => 'Steel', 'type2' => 'Fairy', 'moves' => ['Fairy Lock', 'Tackle', 'Fairy Wind', 'Astonish']],
        'Koffing' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Poison Gas', 'Tackle', 'Smog', 'Smokescreen']],
        'Krokorok' => ['type1' => 'Ground', 'type2' => 'Dark', 'moves' => ['Bite', 'Leer', 'Rage', 'Sand Attack']],
        'Krookodile' => ['type1' => 'Ground', 'type2' => 'Dark', 'moves' => ['Bite', 'Leer', 'Power Trip', 'Rage']],
        'Lapras' => ['type1' => 'Water', 'type2' => 'Ice', 'moves' => ['Growl', 'Sing', 'Water Gun', 'Mist']],
        'Leavanny' => ['type1' => 'Bug', 'type2' => 'Grass', 'moves' => ['Bug Bite', 'False Swipe', 'Razor Leaf', 'Slash']],
        'Liepard' => ['type1' => 'Dark', 'type2' => '', 'moves' => ['Assist', 'Growl', 'Sand Attack', 'Scratch']],
        'Lillipup' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Leer', 'Tackle', 'Odor Sleuth', 'Bite']],
        'Lucario' => ['type1' => 'Fighting', 'type2' => 'Steel', 'moves' => ['Aura Sphere', 'Detect', 'Foresight', 'Laser Focus']],
        'Ludicolo' => ['type1' => 'Water', 'type2' => 'Grass', 'moves' => ['Astonish', 'Growl', 'Mega Drain', 'Nature Power']],
        'Lumineon' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Attract', 'Gust', 'Pound', 'Soak']],
        'Lunatone' => ['type1' => 'Rock', 'type2' => 'Psychic', 'moves' => ['Confusion', 'Harden', 'Moonblast', 'Power Gem']],
        'Luxio' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Leer', 'Tackle', 'Leer', 'Charge']],
        'Luxray' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Charge', 'Electric Terrain', 'Leer', 'Tackle']],
        'Machamp' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Focus Energy', 'Karate Chop', 'Leer', 'Low Kick']],
        'Machoke' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Focus Energy', 'Karate Chop', 'Leer', 'Low Kick']],
        'Machop' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Leer', 'Low Kick', 'Focus Energy', 'Karate Chop']],
        'Magcargo' => ['type1' => 'Fire', 'type2' => 'Rock', 'moves' => ['Earth Power', 'Ember', 'Rock Throw', 'Shell Smash']],
        'Magmar' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Ember', 'Leer', 'Smog', 'Ember']],
        'Magmortar' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Ember', 'Leer', 'Smog', 'Smokescreen']],
        'Magnemite' => ['type1' => 'Electric', 'type2' => 'Steel', 'moves' => ['Supersonic', 'Tackle', 'Thunder Shock', 'Magnet Bomb']],
        'Magneton' => ['type1' => 'Electric', 'type2' => 'Steel', 'moves' => ['Electric Terrain', 'Magnet Bomb', 'Supersonic', 'Tackle']],
        'Makuhita' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Focus Energy', 'Tackle', 'Sand Attack', 'Arm Thrust']],
        'Mandibuzz' => ['type1' => 'Dark', 'type2' => 'Flying', 'moves' => ['Bone Rush', 'Brave Bird', 'Fury Attack', 'Gust']],
        'Manectric' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Electric Terrain', 'Fire Fang', 'Howl', 'Leer']],
        'Mantine' => ['type1' => 'Water', 'type2' => 'Flying', 'moves' => ['Bubble', 'Bubble Beam', 'Bullet Seed', 'Psybeam']],
        'Marowak' => ['type1' => 'Ground', 'type2' => '', 'moves' => ['Bone Club', 'Growl', 'Headbutt', 'Tail Whip']],
        'Mawile' => ['type1' => 'Steel', 'type2' => 'Fairy', 'moves' => ['Astonish', 'Fairy Wind', 'Growl', 'Iron Head']],
        'Medicham' => ['type1' => 'Fighting', 'type2' => 'Psychic', 'moves' => ['Bide', 'Confusion', 'Detect', 'Fire Punch']],
        'Meditite' => ['type1' => 'Fighting', 'type2' => 'Psychic', 'moves' => ['Bide', 'Meditate', 'Confusion', 'Detect']],
        'Meowstic (F)' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Confusion', 'Covet', 'Helping Hand', 'Leer']],
        'Metagross' => ['type1' => 'Steel', 'type2' => 'Psychic', 'moves' => ['Confusion', 'Hammer Arm', 'Magnet Rise', 'Metal Claw']],
        'Metapod' => ['type1' => 'Bug', 'type2' => '', 'moves' => ['Harden', 'Harden', 'Harden', 'Harden']],
        'Mienfoo' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Pound', 'Meditate', 'Detect', 'Fake Out']],
        'Mienshao' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Aura Sphere', 'Detect', 'Fake Out', 'Meditate']],
        'Mightyena' => ['type1' => 'Dark', 'type2' => '', 'moves' => ['Bite', 'Crunch', 'Fire Fang', 'Howl']],
        'Milotic' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Refresh', 'Water Gun', 'Water Pulse', 'Water Sport']],
        'Miltank' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Tackle', 'Growl', 'Defense Curl', 'Stomp']],
        'Misdreavus' => ['type1' => 'Ghost', 'type2' => '', 'moves' => ['Growl', 'Psywave', 'Spite', 'Astonish']],
        'Mismagius' => ['type1' => 'Ghost', 'type2' => '', 'moves' => ['Astonish', 'Growl', 'Lucky Chant', 'Magical Leaf']],
        'Mr. Mime' => ['type1' => 'Psychic', 'type2' => 'Fairy', 'moves' => ['Confusion', 'Barrier', 'Psybeam', 'Psychic']],
        'Muk' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Harden', 'Mud-Slap', 'Poison Gas', 'Pound']],
        'Murkrow' => ['type1' => 'Dark', 'type2' => 'Flying', 'moves' => ['Astonish', 'Peck', 'Pursuit', 'Haze']],
        'Musharna' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Defense Curl', 'Hypnosis', 'Lucky Chant', 'Psybeam']],
        'Nidoking' => ['type1' => 'Poison', 'type2' => 'Ground', 'moves' => ['Double Kick', 'Focus Energy', 'Megahorn', 'Peck']],
        'Nidoqueen' => ['type1' => 'Poison', 'type2' => 'Ground', 'moves' => ['Double Kick', 'Poison Sting', 'Scratch', 'Superpower']],
        'Ninetales' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Confuse Ray', 'Flamethrower', 'Imprison', 'Nasty Plot']],
        'Noivern' => ['type1' => 'Flying', 'type2' => 'Dragon', 'moves' => ['Absorb', 'Boomburst', 'Dragon Pulse', 'Hurricane']],
        'Nosepass' => ['type1' => 'Rock', 'type2' => '', 'moves' => ['Tackle', 'Harden', 'Block', 'Rock Throw']],
        'Octillery' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Aurora Beam', 'Constrict', 'Gunk Shot', 'Octazooka']],
        'Onix' => ['type1' => 'Rock', 'type2' => 'Ground', 'moves' => ['Bind', 'Harden', 'Mud Sport', 'Tackle']],
        'Pachirisu' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Bide', 'Growl', 'Quick Attack', 'Charm']],
        'Patrat' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Tackle', 'Leer', 'Bite', 'Bide']],
        'Pelipper' => ['type1' => 'Water', 'type2' => 'Flying', 'moves' => ['Growl', 'Hurricane', 'Hydro Pump', 'Protect']],
        'Persian' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Bite', 'Fake Out', 'Growl', 'Play Rough']],
        'Pidgeot' => ['type1' => 'Normal', 'type2' => 'Flying', 'moves' => ['Gust', 'Hurricane', 'Quick Attack', 'Sand Attack']],
        'Pidgeotto' => ['type1' => 'Normal', 'type2' => 'Flying', 'moves' => ['Gust', 'Sand Attack', 'Tackle', 'Sand Attack']],
        'Pidgey' => ['type1' => 'Normal', 'type2' => 'Flying', 'moves' => ['Tackle', 'Sand Attack', 'Gust', 'Quick Attack']],
        'Pidove' => ['type1' => 'Normal', 'type2' => 'Flying', 'moves' => ['Gust', 'Growl', 'Leer', 'Quick Attack']],
        'Pikachu' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Tail Whip', 'Thunder Shock', 'Growl', 'Play Nice']],
        'Piloswine' => ['type1' => 'Ice', 'type2' => 'Ground', 'moves' => ['AncientPower', 'Ancient Power', 'Fury Attack', 'Mud Sport']],
        'Politoed' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Bubble Beam', 'Double Slap', 'Hypnosis', 'Perish Song']],
        'Poliwhirl' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Hypnosis', 'Water Gun', 'Water Sport', 'Water Gun']],
        'Poliwrath' => ['type1' => 'Water', 'type2' => 'Fighting', 'moves' => ['Bubble Beam', 'Circle Throw', 'Double Slap', 'Hypnosis']],
        'Ponyta' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Growl', 'Tackle', 'Tail Whip', 'Ember']],
        'Porygon2' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Conversion', 'Conversion 2', 'Defense Curl', 'Magic Coat']],
        'Primeape' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Final Gambit', 'Fling', 'Focus Energy', 'Leer']],
        'Probopass' => ['type1' => 'Rock', 'type2' => 'Steel', 'moves' => ['Block', 'Gravity', 'Iron Defense', 'Magnet Bomb']],
        'Purugly' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Fake Out', 'Growl', 'Scratch', 'Swagger']],
        'Pyroar' => ['type1' => 'Fire', 'type2' => 'Normal', 'moves' => ['Ember', 'Hyper Beam', 'Leer', 'Tackle']],
        'Quagsire' => ['type1' => 'Water', 'type2' => 'Ground', 'moves' => ['Mud Sport', 'Tail Whip', 'Water Gun', 'Mud Sport']],
        'Raichu' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Quick Attack', 'Tail Whip', 'Thunder Shock', 'Thunderbolt']],
        'Rapidash' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Ember', 'Fury Attack', 'Growl', 'Megahorn']],
        'Regice' => ['type1' => 'Ice', 'type2' => '', 'moves' => ['Bulldoze', 'Charge Beam', 'Explosion', 'Icy Wind']],
        'Regirock' => ['type1' => 'Rock', 'type2' => '', 'moves' => ['Bulldoze', 'Charge Beam', 'Explosion', 'Rock Throw']],
        'Registeel' => ['type1' => 'Steel', 'type2' => '', 'moves' => ['Bulldoze', 'Charge Beam', 'Explosion', 'Metal Claw']],
        'Relicanth' => ['type1' => 'Water', 'type2' => 'Rock', 'moves' => ['Flail', 'Harden', 'Head Smash', 'Mud Sport']],
        'Reuniclus' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Dizzy Punch', 'Psywave', 'Reflect', 'Rollout']],
        'Rhydon' => ['type1' => 'Ground', 'type2' => 'Rock', 'moves' => ['Fury Attack', 'Hammer Arm', 'Horn Attack', 'Horn Drill']],
        'Rhyhorn' => ['type1' => 'Ground', 'type2' => 'Rock', 'moves' => ['Horn Attack', 'Tail Whip', 'Fury Attack', 'Scary Face']],
        'Rhyperior' => ['type1' => 'Ground', 'type2' => 'Rock', 'moves' => ['Fury Attack', 'Hammer Arm', 'Horn Attack', 'Horn Drill']],
        'Roserade' => ['type1' => 'Grass', 'type2' => 'Poison', 'moves' => ['Grassy Terrain', 'Magical Leaf', 'Mega Drain', 'Poison Sting']],
        'Sableye' => ['type1' => 'Dark', 'type2' => 'Ghost', 'moves' => ['Leer', 'Scratch', 'Foresight', 'Night Shade']],
        'Salamence' => ['type1' => 'Dragon', 'type2' => 'Flying', 'moves' => ['Bite', 'Dragon Tail', 'Ember', 'Fire Fang']],
        'Sandslash' => ['type1' => 'Ground', 'type2' => '', 'moves' => ['Crush Claw', 'Defense Curl', 'Poison Sting', 'Sand Attack']],
        'Sawk' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Bide', 'Focus Energy', 'Leer', 'Rock Smash']],
        'Sawsbuck (Spring)' => ['type1' => 'Normal', 'type2' => 'Grass', 'moves' => ['Camouflage', 'Growl', 'Horn Leech', 'Megahorn']],
        'Sceptile' => ['type1' => 'Grass', 'type2' => '', 'moves' => ['Absorb', 'Dual Chop', 'Fury Cutter', 'Leaf Storm']],
        'Scizor' => ['type1' => 'Bug', 'type2' => 'Steel', 'moves' => ['Bullet Punch', 'Feint', 'Leer', 'Quick Attack']],
        'Scrafty' => ['type1' => 'Dark', 'type2' => 'Fighting', 'moves' => ['Feint Attack', 'Headbutt', 'Leer', 'Sand Attack']],
        'Scyther' => ['type1' => 'Bug', 'type2' => 'Flying', 'moves' => ['Leer', 'Quick Attack', 'Vacuum Wave', 'Focus Energy']],
        'Seadra' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Bubble', 'Hydro Pump', 'Leer', 'Smokescreen']],
        'Seaking' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Megahorn', 'Peck', 'Poison Jab', 'Supersonic']],
        'Sealeo' => ['type1' => 'Ice', 'type2' => 'Water', 'moves' => ['Defense Curl', 'Growl', 'Powder Snow', 'Swagger']],
        'Seel' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Headbutt', 'Growl', 'Water Sport', 'Icy Wind']],
        'Seviper' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Swagger', 'Wrap', 'Bite', 'Lick']],
        'Sharpedo' => ['type1' => 'Water', 'type2' => 'Dark', 'moves' => ['Bite', 'Feint', 'Focus Energy', 'Leer']],
        'Shedinja' => ['type1' => 'Bug', 'type2' => 'Ghost', 'moves' => ['Absorb', 'Harden', 'Sand Attack', 'Scratch']],
        'Shelgon' => ['type1' => 'Dragon', 'type2' => '', 'moves' => ['Bite', 'Ember', 'Leer', 'Protect']],
        'Shelmet' => ['type1' => 'Bug', 'type2' => '', 'moves' => ['Absorb', 'Acid', 'Bide', 'Curse']],
        'Shiftry' => ['type1' => 'Grass', 'type2' => 'Dark', 'moves' => ['Feint Attack', 'Nasty Plot', 'Razor Leaf', 'Whirlwind']],
        'Shuckle' => ['type1' => 'Bug', 'type2' => 'Rock', 'moves' => ['Bide', 'Constrict', 'Rollout', 'Sticky Web']],
        'Sigilyph' => ['type1' => 'Psychic', 'type2' => 'Flying', 'moves' => ['Gust', 'Miracle Eye', 'Hypnosis', 'Psywave']],
        'Skarmory' => ['type1' => 'Steel', 'type2' => 'Flying', 'moves' => ['Leer', 'Peck', 'Sand Attack', 'Metal Claw']],
        'Slaking' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Encore', 'Fling', 'Hammer Arm', 'Punishment']],
        'Slowbro' => ['type1' => 'Water', 'type2' => 'Psychic', 'moves' => ['Curse', 'Growl', 'Heal Pulse', 'Tackle']],
        'Slowking' => ['type1' => 'Water', 'type2' => 'Psychic', 'moves' => ['Curse', 'Heal Pulse', 'Hidden Power', 'Power Gem']],
        'Slugma' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Smog', 'Yawn', 'Ember', 'Rock Throw']],
        'Sneasel' => ['type1' => 'Dark', 'type2' => 'Ice', 'moves' => ['Leer', 'Scratch', 'Taunt', 'Quick Attack']],
        'Snorlax' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Tackle', 'Defense Curl', 'Amnesia', 'Lick']],
        'Snover' => ['type1' => 'Grass', 'type2' => 'Ice', 'moves' => ['Leer', 'Powder Snow', 'Razor Leaf', 'Icy Wind']],
        'Solrock' => ['type1' => 'Rock', 'type2' => 'Psychic', 'moves' => ['Confusion', 'Flare Blitz', 'Harden', 'Rock Throw']],
        'Spiritomb' => ['type1' => 'Ghost', 'type2' => 'Dark', 'moves' => ['Confuse Ray', 'Curse', 'Pursuit', 'Shadow Sneak']],
        'Staraptor' => ['type1' => 'Normal', 'type2' => 'Flying', 'moves' => ['Close Combat', 'Growl', 'Quick Attack', 'Tackle']],
        'Starmie' => ['type1' => 'Water', 'type2' => 'Psychic', 'moves' => ['Hydro Pump', 'Rapid Spin', 'Recover', 'Spotlight']],
        'Staryu' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Harden', 'Tackle', 'Water Gun', 'Rapid Spin']],
        'Steelix' => ['type1' => 'Steel', 'type2' => 'Ground', 'moves' => ['Bind', 'Fire Fang', 'Harden', 'Ice Fang']],
        'Surskit' => ['type1' => 'Bug', 'type2' => 'Water', 'moves' => ['Bubble', 'Quick Attack', 'Sweet Scent', 'Water Sport']],
        'Swalot' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Body Slam', 'Gunk Shot', 'Poison Gas', 'Pound']],
        'Swampert' => ['type1' => 'Water', 'type2' => 'Ground', 'moves' => ['Growl', 'Hammer Arm', 'Mud Shot', 'Mud-Slap']],
        'Swanna' => ['type1' => 'Water', 'type2' => 'Flying', 'moves' => ['Defog', 'Water Gun', 'Water Sport', 'Wing Attack']],
        'Swellow' => ['type1' => 'Normal', 'type2' => 'Flying', 'moves' => ['Air Slash', 'Brave Bird', 'Focus Energy', 'Growl']],
        'Swoobat' => ['type1' => 'Psychic', 'type2' => 'Flying', 'moves' => ['Assurance', 'Confusion', 'Gust', 'Odor Sleuth']],
        'Sylveon' => ['type1' => 'Fairy', 'type2' => '', 'moves' => ['Disarming Voice', 'Fairy Wind', 'Helping Hand', 'Tackle']],
        'Talonflame' => ['type1' => 'Fire', 'type2' => 'Flying', 'moves' => ['Brave Bird', 'Ember', 'Flare Blitz', 'Growl']],
        'Tangela' => ['type1' => 'Grass', 'type2' => '', 'moves' => ['AncientPower', 'Constrict', 'Ingrain', 'Sleep Powder']],
        'Tentacruel' => ['type1' => 'Water', 'type2' => 'Poison', 'moves' => ['Acid', 'Constrict', 'Poison Sting', 'Reflect Type']],
        'Throh' => ['type1' => 'Fighting', 'type2' => '', 'moves' => ['Bide', 'Bind', 'Focus Energy', 'Leer']],
        'Togekiss' => ['type1' => 'Fairy', 'type2' => 'Flying', 'moves' => ['After You', 'Air Slash', 'Aura Sphere', 'Extreme Speed']],
        'Torkoal' => ['type1' => 'Fire', 'type2' => '', 'moves' => ['Ember', 'Smog', 'Withdraw', 'Rapid Spin']],
        'Tropius' => ['type1' => 'Grass', 'type2' => 'Flying', 'moves' => ['Growth', 'Gust', 'Leaf Storm', 'Leer']],
        'Turtwig' => ['type1' => 'Grass', 'type2' => '', 'moves' => ['Tackle', 'Withdraw', 'Absorb', 'Razor Leaf']],
        'Tyrantrum' => ['type1' => 'Rock', 'type2' => 'Dragon', 'moves' => ['Head Smash', 'Roar', 'Rock Slide', 'Stomp']],
        'Tyrunt' => ['type1' => 'Rock', 'type2' => 'Dragon', 'moves' => ['Tackle', 'Tail Whip', 'Roar', 'Stomp']],
        'Umbreon' => ['type1' => 'Dark', 'type2' => '', 'moves' => ['Helping Hand', 'Pursuit', 'Tackle', 'Tail Whip']],
        'Venomoth' => ['type1' => 'Bug', 'type2' => 'Poison', 'moves' => ['Bug Buzz', 'Disable', 'Foresight', 'Gust']],
        'Venusaur' => ['type1' => 'Grass', 'type2' => 'Poison', 'moves' => ['Growl', 'Leech Seed', 'Petal Dance', 'Tackle']],
        'Vespiquen' => ['type1' => 'Bug', 'type2' => 'Flying', 'moves' => ['Confuse Ray', 'Destiny Bond', 'Fell Stinger', 'Gust']],
        'Victreebel' => ['type1' => 'Grass', 'type2' => 'Poison', 'moves' => ['Leaf Tornado', 'Razor Leaf', 'Sleep Powder', 'Spit Up']],
        'Vigoroth' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Encore', 'Focus Energy', 'Reversal', 'Scratch']],
        'Vileplume' => ['type1' => 'Grass', 'type2' => 'Poison', 'moves' => ['Aromatherapy', 'Mega Drain', 'Poison Powder', 'Stun Spore']],
        'Vivillon (Meadow)' => ['type1' => 'Bug', 'type2' => 'Flying', 'moves' => ['Gust', 'Poison Powder', 'Powder', 'Sleep Powder']],
        'Voltorb' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Charge', 'Tackle', 'Sonic Boom', 'Eerie Impulse']],
        'Wailord' => ['type1' => 'Water', 'type2' => '', 'moves' => ['Growl', 'Heavy Slam', 'Noble Roar', 'Rollout']],
        'Walrein' => ['type1' => 'Ice', 'type2' => 'Water', 'moves' => ['Crunch', 'Defense Curl', 'Growl', 'Ice Fang']],
        'Weavile' => ['type1' => 'Dark', 'type2' => 'Ice', 'moves' => ['Assurance', 'Embargo', 'Leer', 'Quick Attack']],
        'Weepinbell' => ['type1' => 'Grass', 'type2' => 'Poison', 'moves' => ['Growth', 'Vine Whip', 'Wrap', 'Growth']],
        'Weezing' => ['type1' => 'Poison', 'type2' => '', 'moves' => ['Double Hit', 'Poison Gas', 'Smog', 'Smokescreen']],
        'Whirlipede' => ['type1' => 'Bug', 'type2' => 'Poison', 'moves' => ['Defense Curl', 'Iron Defense', 'Poison Sting', 'Rollout']],
        'Whiscash' => ['type1' => 'Water', 'type2' => 'Ground', 'moves' => ['Belch', 'Mud-Slap', 'Mud Sport', 'Thrash']],
        'Wigglytuff' => ['type1' => 'Normal', 'type2' => 'Fairy', 'moves' => ['Defense Curl', 'Disable', 'Double-Edge', 'Double Slap']],
        'Wobbuffet' => ['type1' => 'Psychic', 'type2' => '', 'moves' => ['Counter', 'Destiny Bond', 'Mirror Coat', 'Safeguard']],
        'Xatu' => ['type1' => 'Psychic', 'type2' => 'Flying', 'moves' => ['Air Slash', 'Leer', 'Night Shade', 'Peck']],
        'Yanmega' => ['type1' => 'Bug', 'type2' => 'Flying', 'moves' => ['AncientPower', 'Air Slash', 'Bug Bite', 'Bug Buzz']],
        'Zangoose' => ['type1' => 'Normal', 'type2' => '', 'moves' => ['Leer', 'Scratch', 'Quick Attack', 'Fury Cutter']],
        'Zebstrika' => ['type1' => 'Electric', 'type2' => '', 'moves' => ['Charge', 'Ion Deluge', 'Quick Attack', 'Tail Whip']],
    ];
    return $species;
}

function pv_battle_catalog_required_badge_ids(): array
{
    return range(1, 95);
}

function pv_battle_catalog_by_route(string $route): ?array
{
    $needle = trim($route);
    if ($needle === '') return null;
    foreach (pv_battle_catalog() as $id => $trainer) {
        if (hash_equals((string)$trainer['route'], $needle)) {
            $trainer['id'] = (int)$id;
            return $trainer;
        }
    }
    return null;
}

function pv_battle_catalog_all_completed(array $badges): bool
{
    foreach (pv_battle_catalog_required_badge_ids() as $id) {
        if ((int)($badges['g' . $id] ?? 0) !== 1) return false;
    }
    return true;
}

function pv_battle_catalog_progress(array $badges, ?array $ids = null): array
{
    $ids = $ids ?? pv_battle_catalog_required_badge_ids();
    $total = count($ids);
    $done = 0;
    foreach ($ids as $id) if ((int)($badges['g' . (int)$id] ?? 0) === 1) $done++;
    return ['done' => $done, 'total' => $total, 'percent' => $total > 0 ? (int)floor(($done / $total) * 100) : 0];
}

function pv_battle_catalog_badges(mysqli $db, int $uid): array
{
    $uid = max(1, $uid);
    $badges = ['id' => $uid];
    foreach (pv_battle_catalog_required_badge_ids() as $id) $badges['g' . $id] = 0;
    $stmt = $db->prepare('SELECT * FROM badges WHERE id=? LIMIT 1');
    if (!$stmt) return $badges;
    $stmt->bind_param('i', $uid);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $stmt->close();
    if (is_array($row)) {
        foreach ($badges as $key => $value) if (array_key_exists($key, $row)) $badges[$key] = (int)$row[$key];
    }
    return $badges;
}

function pv_battle_catalog_storage_status(mysqli $db): array
{
    $version = 0;
    $meta = @$db->query("SELECT version FROM pv_schema_meta WHERE id=1 LIMIT 1");
    if ($meta instanceof mysqli_result && ($row = $meta->fetch_assoc())) $version = (int)($row['version'] ?? 0);

    $hasGymPokemon = false;
    $r = @$db->query("SHOW TABLES LIKE 'gympokemon'");
    if ($r instanceof mysqli_result) $hasGymPokemon = $r->num_rows > 0;

    $hasG95 = false;
    $r = @$db->query("SHOW COLUMNS FROM badges LIKE 'g95'");
    if ($r instanceof mysqli_result) $hasG95 = $r->num_rows > 0;

    $trainers = 0;
    $r = @$db->query('SELECT COUNT(*) c FROM gym WHERE id BETWEEN 1 AND 95');
    if ($r instanceof mysqli_result && ($row = $r->fetch_assoc())) $trainers = (int)($row['c'] ?? 0);

    $pokemon = 0;
    if ($hasGymPokemon) {
        $r = @$db->query('SELECT COUNT(*) c FROM gympokemon WHERE owner BETWEEN 1 AND 95');
        if ($r instanceof mysqli_result && ($row = $r->fetch_assoc())) $pokemon = (int)($row['c'] ?? 0);
    }

    return [
        'ready' => $version >= 24 && $hasGymPokemon && $hasG95 && $trainers === 95 && $pokemon === 402,
        'schema_version' => $version,
        'trainers' => $trainers,
        'pokemon' => $pokemon,
        'expected_trainers' => 95,
        'expected_pokemon' => 402,
    ];
}

function pv_battle_catalog_seed(mysqli $db, array &$changes): void
{
    $catalog = pv_battle_catalog();
    $species = pv_battle_species_data();

    // This table is reserved exclusively for reconstructed Battle Arena NPCs.
    // Clear the reserved owner range before seeding so Upgrade / Repair remains
    // an exact synchronization operation even after an interrupted/older seed.
    if (!$db->query('DELETE FROM gympokemon WHERE owner BETWEEN 1 AND 95')) {
        throw new RuntimeException('Could not clear stale Battle Arena NPC Pokémon: ' . $db->error);
    }
    $gym = $db->prepare('INSERT INTO gym (id,leader,s1,s2,s3,s4,s5,s6) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE leader=VALUES(leader),s1=VALUES(s1),s2=VALUES(s2),s3=VALUES(s3),s4=VALUES(s4),s5=VALUES(s5),s6=VALUES(s6)');
    $poke = $db->prepare('INSERT INTO gympokemon (id,owner,name,a1,a2,a3,a4,lvl,exp,t1,t2,rowner) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE owner=VALUES(owner),name=VALUES(name),a1=VALUES(a1),a2=VALUES(a2),a3=VALUES(a3),a4=VALUES(a4),lvl=VALUES(lvl),exp=VALUES(exp),t1=VALUES(t1),t2=VALUES(t2),rowner=VALUES(rowner)');
    if (!$gym || !$poke) {
        if ($gym) $gym->close();
        if ($poke) $poke->close();
        throw new RuntimeException('Battle Arena seed statements could not be prepared.');
    }

    foreach ($catalog as $id => $trainer) {
        $ids = [];
        foreach ((array)$trainer['roster'] as $slot => $name) {
            $pokemonId = 1000000 + ((int)$id * 10) + ((int)$slot + 1);
            $ids[] = $pokemonId;
            $meta = $species[(string)$name] ?? null;
            if (!is_array($meta)) throw new RuntimeException('Missing Battle Arena species metadata for ' . $name);
            $moves = array_pad((array)$meta['moves'], 4, 'Tackle');
            $level = max(1, (int)$trainer['level']);
            $exp = $level * $level * $level;
            $type1 = (string)$meta['type1'];
            $type2 = (string)$meta['type2'];
            $ownerName = (string)$trainer['display'];
            $name = (string)$name;
            $a1=(string)$moves[0]; $a2=(string)$moves[1]; $a3=(string)$moves[2]; $a4=(string)$moves[3];
            $owner=(int)$id;
            $poke->bind_param('iisssssiiiss', $pokemonId,$owner,$name,$a1,$a2,$a3,$a4,$level,$exp,$type1,$type2,$ownerName);
            if (!$poke->execute()) throw new RuntimeException('Could not seed Battle Arena Pokémon for ' . $ownerName . ': ' . $poke->error);
        }
        $slots = array_pad($ids, 6, null);
        $leader=(string)$trainer['route'];
        $gid=(int)$id;
        $s1=$slots[0];$s2=$slots[1];$s3=$slots[2];$s4=$slots[3];$s5=$slots[4];$s6=$slots[5];
        $gym->bind_param('isiiiiii', $gid,$leader,$s1,$s2,$s3,$s4,$s5,$s6);
        if (!$gym->execute()) throw new RuntimeException('Could not seed Battle Arena trainer ' . $leader . ': ' . $gym->error);
    }
    $gym->close(); $poke->close();
    $changes[] = 'Synchronized 95 Battle Arena opponents and 402 deterministic NPC Pokémon';
}

function pv_battle_catalog_award(mysqli $db, int $uid, int $opponentId): array
{
    if ($uid <= 0 || !isset(pv_battle_catalog()[$opponentId])) {
        return ['awarded' => false, 'already' => false, 'all_complete' => false, 'progress' => ['done'=>0,'total'=>95,'percent'=>0]];
    }
    $column = 'g' . $opponentId;
    $db->begin_transaction();
    try {
        $stmt = $db->prepare('INSERT INTO badges (id) VALUES (?) ON DUPLICATE KEY UPDATE id=VALUES(id)');
        if (!$stmt) throw new RuntimeException('Badge row could not be prepared.');
        $stmt->bind_param('i',$uid); $stmt->execute(); $stmt->close();

        $stmt = $db->prepare('SELECT * FROM badges WHERE id=? FOR UPDATE');
        if (!$stmt) throw new RuntimeException('Badge progression could not be locked.');
        $stmt->bind_param('i',$uid); $stmt->execute(); $badges=$stmt->get_result()->fetch_assoc() ?: []; $stmt->close();
        $already = (int)($badges[$column] ?? 0) === 1;
        if (!$already) {
            if (!$db->query('UPDATE badges SET `' . $column . '`=1 WHERE id=' . (int)$uid)) throw new RuntimeException('Badge progression could not be updated.');
            $badges[$column] = 1;
        }
        $complete = pv_battle_catalog_all_completed($badges);
        if ($complete) {
            $stmt=$db->prepare('UPDATE members SET badges=1 WHERE id=?');
            if (!$stmt) throw new RuntimeException('Legendary progression could not be updated.');
            $stmt->bind_param('i',$uid); $stmt->execute(); $stmt->close();
        }
        $db->commit();
        if ($complete) $_SESSION['map_preferences'][0] = 1;
        return ['awarded'=>!$already,'already'=>$already,'all_complete'=>$complete,'progress'=>pv_battle_catalog_progress($badges)];
    } catch (Throwable $e) {
        $db->rollback();
        throw $e;
    }
}
