<?php
declare(strict_types=1);
require_once __DIR__ . '/gameplay.php';
require_once __DIR__ . '/combat.php';
require_once __DIR__ . '/world_maps.php';


function pv_wild_return_url(?array $state=null): string
{
    $world=trim((string)($state['world']??($_SESSION['world_key']??'vortex')));
    $area=trim((string)($state['area']??($_SESSION['world_area']??'')));
    if($area!=='' && function_exists('pv_world_is_region_world') && pv_world_is_region_world($world) && function_exists('pv_world_area_url')){
        return pv_world_area_url($world,$area);
    }
    $map=max(1,min(25,(int)($state['map']??($_SESSION['map']??1))));
    return pv_url('map.php?map='.$map);
}

function pv_wild_location_label(?array $state=null): string
{
    $world=trim((string)($state['world']??''));
    $area=trim((string)($state['area']??''));
    if($area!=='' && function_exists('pv_world_is_region_world') && pv_world_is_region_world($world)){
        $label=ucfirst($world);
        if(function_exists('pv_world_definition')){$worldDef=pv_world_definition($world);if(is_array($worldDef))$label=(string)($worldDef['label']??$label);}
        if(function_exists('pv_world_area')){$def=pv_world_area($world,$area);if(is_array($def))return $label.' · '.(string)$def['name'];}
        return $label.' · '.ucwords(str_replace('-',' ',$area));
    }
    return 'Map '.max(1,min(25,(int)($state['map']??($_SESSION['map']??1))));
}

function pv_wild_state(): ?array
{
    $state = $_SESSION['pv_wild_battle'] ?? null;
    return is_array($state) ? $state : null;
}

function pv_wild_save(array $state): void
{
    $_SESSION['pv_wild_battle'] = $state;
}

function pv_wild_clear(): void
{
    unset($_SESSION['pv_wild_battle']);
}

/**
 * Return the exact level generated by the authoritative map encounter.
 *
 * Region worlds legitimately use early-game levels below 5. Never coerce a
 * valid encounter upward here: the level shown by the scanner must be the
 * same level used for battle HP/damage, capture creation and the result
 * ledger. The v25.2.1 progression contract caps wild encounters at level 24;
 * stale or corrupt pending encounters above that cap fail closed and must be rescanned
 * instead of being silently altered after the scanner has shown a different level.
 */
function pv_wild_authoritative_encounter_level(array $pending): int
{
    if (!array_key_exists('level', $pending)) {
        throw new RuntimeException('The wild encounter level is missing. Return to the map and scan again.');
    }
    $level = (int)$pending['level'];
    if ($level < 1 || $level > PV_WILD_LEVEL_CAP) {
        throw new RuntimeException('The wild encounter level is invalid. Return to the map and scan again.');
    }
    return $level;
}

function pv_wild_result_row(mysqli $db, string $battleId, int $uid): ?array
{
    if ($battleId === '' || $uid <= 0) return null;
    $stmt = $db->prepare('SELECT battle_id,user_id,outcome,wild_pid,wild_name,wild_level,reward_exp,reward_money,captured_pokemon_id,created_at FROM wild_battle_results WHERE battle_id=? AND user_id=? LIMIT 1');
    if (!$stmt) return null;
    $stmt->bind_param('si', $battleId, $uid);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $stmt->close();
    return $row ?: null;
}

function pv_wild_result_insert(mysqli $db, array $state, int $uid, string $outcome, int $rewardExp = 0, int $rewardMoney = 0, int $capturedPokemonId = 0): void
{
    $battleId = (string)($state['id'] ?? '');
    $wild = (array)($state['wild'] ?? []);
    $pid = (int)($wild['pid'] ?? 0);
    $name = (string)($wild['display_name'] ?? $wild['name'] ?? 'Wild Pokémon');
    $level = max(1, (int)($wild['level'] ?? 1));
    $createdAt = time();
    $stmt = $db->prepare('INSERT INTO wild_battle_results (battle_id,user_id,outcome,wild_pid,wild_name,wild_level,reward_exp,reward_money,captured_pokemon_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)');
    if (!$stmt) { pv_log('Wild battle ledger prepare failed: ' . $db->error); throw new RuntimeException('Battle records are temporarily unavailable. Return to the map and try again.'); }
    $stmt->bind_param('sisisiiiii', $battleId, $uid, $outcome, $pid, $name, $level, $rewardExp, $rewardMoney, $capturedPokemonId, $createdAt);
    if (!$stmt->execute()) {
        $message = $stmt->error;
        $stmt->close();
        pv_log('Wild battle ledger insert failed: ' . $message);
        throw new RuntimeException('The battle result could not be saved. Please retry from the current battle screen.');
    }
    $stmt->close();
}

function pv_wild_hp_max(string $name, int $level, int $hpIv = 0): int
{
    $level = max(1, min(100, $level));
    $bonus = stripos($name, 'Shiny ') === 0 ? $level : 0;
    return max(20, ($level * 4) + $bonus + intdiv(max(0, min(31, $hpIv)), 2));
}

function pv_wild_type_effectiveness(string $attackType, string $defenderType): float
{
    return pv_combat_type_effectiveness($attackType, $defenderType);
}

function pv_wild_move_data(mysqli $db, string $move, string $fallbackType = 'Normal'): array
{
    return pv_combat_move_data($db, $move, $fallbackType);
}

function pv_wild_damage(array $attacker, array $defender, array $move): array
{
    $accuracy = max(1, min(100, (int)($move['accuracy'] ?? 100)));
    if (random_int(1,100) > $accuracy) {
        return ['damage'=>0,'hit'=>false,'critical'=>false,'effectiveness'=>1.0];
    }
    $power = max(0, (int)($move['power'] ?? 0));
    if ($power <= 0) {
        return ['damage'=>0,'hit'=>true,'critical'=>false,'effectiveness'=>1.0];
    }

    $level = max(1, (int)($attacker['level'] ?? 1));
    $type = (string)($move['type'] ?? 'Normal');
    $stab = (strcasecmp($type, (string)($attacker['type1'] ?? '')) === 0 || strcasecmp($type, (string)($attacker['type2'] ?? '')) === 0) ? 1.5 : 1.0;
    $effectiveness = pv_wild_type_effectiveness($type, (string)($defender['type1'] ?? ''))
        * pv_wild_type_effectiveness($type, (string)($defender['type2'] ?? ''));
    $critical = random_int(1,16) === 1;
    $crit = $critical ? 1.5 : 1.0;
    $variance = random_int(85,100) / 100;
    $base = (((2 * $level / 5) + 2) * $power / 50) + 2;
    $damage = $effectiveness <= 0.0 ? 0 : max(1, (int)floor($base * $stab * $effectiveness * $crit * $variance));
    return ['damage'=>$damage,'hit'=>true,'critical'=>$critical,'effectiveness'=>$effectiveness];
}

function pv_wild_log(array &$state, string $text, string $tone = 'neutral'): void
{
    $state['log'][] = ['text'=>$text,'tone'=>$tone,'time'=>time()];
    if (count($state['log']) > 18) $state['log'] = array_slice($state['log'], -18);
}

function pv_wild_team(mysqli $db, int $uid): array
{
    $stmt = $db->prepare('SELECT s1,s2,s3,s4,s5,s6 FROM members WHERE id=? LIMIT 1');
    if (!$stmt) return [];
    $stmt->bind_param('i',$uid);
    $stmt->execute();
    $slots = $stmt->get_result()->fetch_assoc() ?: [];
    $stmt->close();

    $team = [];
    for ($slot=1; $slot<=6; $slot++) {
        $id = (int)($slots['s'.$slot] ?? 0);
        if ($id <= 0) continue;
        $stmt = $db->prepare('SELECT p.id,p.pid,p.name,p.a1,p.a2,p.a3,p.a4,p.lvl,p.t1,p.t2,COALESCE(ps.hp_iv,0) hp_iv FROM pokemon p LEFT JOIN pokemon_stats ps ON ps.id=p.id WHERE p.id=? AND CAST(p.owner AS UNSIGNED)=? LIMIT 1');
        if (!$stmt) continue;
        $stmt->bind_param('ii',$id,$uid);
        $stmt->execute();
        $row = $stmt->get_result()->fetch_assoc();
        $stmt->close();
        if (!$row) continue;
        $name=(string)$row['name']; $level=max(1,(int)$row['lvl']);
        $maxHp=pv_wild_hp_max($name,$level,(int)$row['hp_iv']);
        $team[$id]=[
            'id'=>$id,'pid'=>(int)$row['pid'],'name'=>$name,'display_name'=>$name,'sprite_name'=>$name,
            'level'=>$level,'type1'=>(string)$row['t1'],'type2'=>(string)$row['t2'],
            'moves'=>array_values(array_filter([(string)$row['a1'],(string)$row['a2'],(string)$row['a3'],(string)$row['a4']], static fn($v)=>trim($v)!=='')),
            'max_hp'=>$maxHp,'hp'=>$maxHp,'status'=>'none','slot'=>$slot,
        ];
    }
    return $team;
}

function pv_wild_start(mysqli $db, int $uid, string $token): array
{
    $pending = $_SESSION['pv_pending_wild_encounter'] ?? null;
    if (!is_array($pending) || !hash_equals((string)($pending['token'] ?? ''), $token)) {
        throw new RuntimeException('That wild encounter is no longer active. Move again on the map to scan for another Pokémon.');
    }
    if (!empty($pending['consumed']) || (time() - (int)($pending['created_at'] ?? 0)) > 900) {
        unset($_SESSION['pv_pending_wild_encounter']);
        throw new RuntimeException('That wild signal has expired. Return to the map and scan again.');
    }

    $pid=(int)($pending['pid'] ?? 0);
    $stmt=$db->prepare('SELECT id,name,type1,type2,a1,a2,a3,a4 FROM pguide WHERE id=? LIMIT 1');
    if(!$stmt) throw new RuntimeException('Wild Pokémon data is temporarily unavailable.');
    $stmt->bind_param('i',$pid); $stmt->execute(); $guide=$stmt->get_result()->fetch_assoc(); $stmt->close();
    if(!$guide) throw new RuntimeException('This wild Pokémon is not available for battle right now. Return to the map and scan again.');

    $team=pv_wild_team($db,$uid);
    if(!$team) throw new RuntimeException('Add at least one Pokémon to your active team before starting a wild battle.');
    $activeId=(int)array_key_first($team);
    $level=pv_wild_authoritative_encounter_level($pending);
    $canonical=(string)$guide['name'];
    $display=trim((string)($pending['display_name'] ?? $canonical)) ?: $canonical;
    $sprite=trim((string)($pending['sprite_name'] ?? $display)) ?: $canonical;
    $maxHp=pv_wild_hp_max($canonical,$level,random_int(0,31));
    $wild=[
        'pid'=>(int)$guide['id'],'name'=>$canonical,'display_name'=>$display,'sprite_name'=>$sprite,'level'=>$level,
        'type1'=>(string)$guide['type1'],'type2'=>(string)$guide['type2'],
        'moves'=>array_values(array_filter([(string)$guide['a1'],(string)$guide['a2'],(string)$guide['a3'],(string)$guide['a4']], static fn($v)=>trim($v)!=='')),
        'max_hp'=>$maxHp,'hp'=>$maxHp,'status'=>'none',
    ];
    if(!$wild['moves']) $wild['moves']=['Tackle'];

    $state=[
        'id'=>bin2hex(random_bytes(16)),'status'=>'active','created_at'=>time(),'updated_at'=>time(),'turn'=>1,
        'map'=>max(0,min(25,(int)($pending['map'] ?? ($_SESSION['map'] ?? 1)))),
        'world'=>trim((string)($pending['world']??'vortex'))?:'vortex',
        'area'=>trim((string)($pending['area']??'')),
        'encounter_token'=>$token,'wild'=>$wild,'team'=>$team,'active_id'=>$activeId,
        'participants'=>[$activeId=>true],'log'=>[],'result'=>null,'rewarded'=>false,
        'fx'=>['id'=>bin2hex(random_bytes(6)),'turn'=>0,'action'=>'intro','detail'=>'','player'=>null,'enemy'=>null,'capture'=>null,'heal'=>null,'switch'=>null,'created_at'=>time()],
    ];
    pv_wild_log($state,'Wild '.$display.' appeared at level '.$level.'.','accent');
    pv_wild_log($state,'Go, '.$team[$activeId]['name'].'!');
    pv_admin_world_claim_spawn($db,$uid,$pending);
    $_SESSION['pv_pending_wild_encounter']['consumed']=true;
    pv_wild_save($state);
    return $state;
}

function pv_wild_effectiveness_text(float $value): string
{
    if ($value <= 0.0) return ' It had no effect.';
    if ($value >= 2.0) return " It's super effective!";
    if ($value < 1.0) return " It's not very effective.";
    return '';
}

function pv_wild_attack_turn(mysqli $db, array &$state, int $attackerId, string $moveName): void
{
    if (($state['status'] ?? '') !== 'active') return;
    if (!isset($state['team'][$attackerId]) || $attackerId !== (int)$state['active_id']) return;
    $player =& $state['team'][$attackerId];
    $wild =& $state['wild'];
    if ((int)$player['hp'] <= 0 || (int)$wild['hp'] <= 0) return;

    if (!in_array($moveName,$player['moves'],true)) throw new RuntimeException('Choose one of your active Pokémon’s moves.');
    $move=pv_wild_move_data($db,$moveName,(string)$player['type1']);
    $result=pv_wild_damage($player,$wild,$move);
    $state['fx']['player']=[
        'move'=>(string)$move['attack'],'type'=>(string)$move['type'],'hit'=>(bool)$result['hit'],
        'damage'=>(int)$result['damage'],'critical'=>(bool)$result['critical'],'effectiveness'=>(float)$result['effectiveness'],
    ];
    if(!$result['hit']) {
        pv_wild_log($state,$player['name'].' used '.$move['attack'].', but it missed.','muted');
    } else {
        $wild['hp']=max(0,(int)$wild['hp']-(int)$result['damage']);
        $msg=$player['name'].' used '.$move['attack'].' and dealt '.(int)$result['damage'].' damage.';
        if($result['critical']) $msg.=' Critical hit!';
        $msg.=pv_wild_effectiveness_text((float)$result['effectiveness']);
        pv_wild_log($state,$msg,$result['effectiveness']>=2?'good':'neutral');
    }
    if((int)$wild['hp']<=0){
        $state['fx']['enemy_fainted']=true;
        pv_wild_finalize_win($db,$state);
        return;
    }
    pv_wild_enemy_turn($db,$state);
}

function pv_wild_enemy_turn(mysqli $db, array &$state): void
{
    if (($state['status'] ?? '') !== 'active') return;
    $activeId=(int)$state['active_id'];
    if(!isset($state['team'][$activeId])) return;
    $player =& $state['team'][$activeId];
    $wild =& $state['wild'];
    if((int)$player['hp']<=0 || (int)$wild['hp']<=0) return;

    $moves=$wild['moves'];
    $damaging=[];
    foreach($moves as $m){
        $md=pv_wild_move_data($db,(string)$m,(string)$wild['type1']);
        if((int)$md['power']>0) $damaging[]=$m;
    }
    $pool=$damaging ?: $moves;
    $moveName=(string)$pool[random_int(0,count($pool)-1)];
    $move=pv_wild_move_data($db,$moveName,(string)$wild['type1']);
    $result=pv_wild_damage($wild,$player,$move);
    $state['fx']['enemy']=[
        'move'=>(string)$move['attack'],'type'=>(string)$move['type'],'hit'=>(bool)$result['hit'],
        'damage'=>(int)$result['damage'],'critical'=>(bool)$result['critical'],'effectiveness'=>(float)$result['effectiveness'],
    ];
    if(!$result['hit']) {
        pv_wild_log($state,'Wild '.$wild['display_name'].' used '.$move['attack'].', but it missed.','muted');
    } else {
        $player['hp']=max(0,(int)$player['hp']-(int)$result['damage']);
        $msg='Wild '.$wild['display_name'].' used '.$move['attack'].' and dealt '.(int)$result['damage'].' damage.';
        if($result['critical']) $msg.=' Critical hit!';
        $msg.=pv_wild_effectiveness_text((float)$result['effectiveness']);
        pv_wild_log($state,$msg,$result['effectiveness']>=2?'danger':'neutral');
    }

    if((int)$player['hp']<=0){
        $state['fx']['player_fainted']=true;
        pv_wild_log($state,$player['name'].' fainted.','danger');
        foreach($state['team'] as $id=>$member){
            if((int)$member['hp']>0){
                $state['active_id']=(int)$id;
                $state['fx']['auto_switch']=['name'=>(string)$member['name'],'pokemon_id'=>(int)$id];
                $state['participants'][(int)$id]=true;
                pv_wild_log($state,$member['name'].' entered the battle.','accent');
                return;
            }
        }
        pv_wild_finalize_loss($db,$state);
    }
}

function pv_wild_finalize_win(mysqli $db, array &$state): void
{
    if (($state['status'] ?? '') !== 'active' || !empty($state['rewarded'])) return;
    $uid=(int)$_SESSION['myid'];
    $battleId=(string)($state['id'] ?? '');

    // If a prior request committed the reward but the browser lost the response,
    // rebuild the session result from the durable ledger instead of paying twice.
    $existing=pv_wild_result_row($db,$battleId,$uid);
    if($existing && (string)$existing['outcome']==='won'){
        $state['status']='won';$state['rewarded']=true;
        $state['result']=['title'=>'Battle won','message'=>'Wild '.$state['wild']['display_name'].' was defeated.','exp'=>(int)$existing['reward_exp'],'money'=>(int)$existing['reward_money']];
        pv_wild_log($state,'Your battle result has been restored.','good');
        return;
    }
    if($existing) throw new RuntimeException('This encounter has already been resolved. Return to the map to continue exploring.');

    $wildLevel=max(1,(int)$state['wild']['level']);
    $exp=max(75,$wildLevel*55);
    $money=max(50,$wildLevel*22+random_int(25,125));
    $participantIds=array_map('intval',array_keys(array_filter($state['participants'])));

    $db->begin_transaction();
    try {
        pv_wild_result_insert($db,$state,$uid,'won',$exp,$money,0);
        $stmt=$db->prepare('UPDATE members SET battle=battle+1,money=money+? WHERE id=?');
        if(!$stmt) throw new RuntimeException('Could not record battle rewards.');
        $stmt->bind_param('ii',$money,$uid); $stmt->execute(); $stmt->close();
        foreach($participantIds as $id){
            $stmt=$db->prepare('UPDATE pokemon SET lvl=LEAST(100,GREATEST(1,FLOOR((exp+?)/500))), exp=exp+? WHERE id=? AND CAST(owner AS UNSIGNED)=?');
            if(!$stmt) throw new RuntimeException('Could not record Pokémon experience.');
            $stmt->bind_param('iiii',$exp,$exp,$id,$uid); $stmt->execute(); $stmt->close();
            $stmt=$db->prepare('UPDATE pokemon_stats SET happiness=LEAST(255,happiness+1) WHERE id=?');
            if($stmt){$stmt->bind_param('i',$id);$stmt->execute();$stmt->close();}
        }
        $db->commit();
    } catch(Throwable $e){
        $db->rollback();
        // Duplicate-key races are recoverable if another request already made
        // the exact same battle durable.
        $existing=pv_wild_result_row($db,$battleId,$uid);
        if($existing && (string)$existing['outcome']==='won'){
            $state['status']='won';$state['rewarded']=true;
            $state['result']=['title'=>'Battle won','message'=>'Wild '.$state['wild']['display_name'].' was defeated.','exp'=>(int)$existing['reward_exp'],'money'=>(int)$existing['reward_money']];
            return;
        }
        pv_log('Wild battle reward failure: '.$e->getMessage());
        throw new RuntimeException('The battle ended, but the rewards could not be saved. Please try again from the current battle screen.');
    }
    try { pv_recalculate_trainer_progress($db,$uid,true); }
    catch(Throwable $e){ pv_log('Wild battle progress refresh failed after committed win: '.$e->getMessage()); }
    $state['status']='won'; $state['rewarded']=true;
    $state['result']=['title'=>'Battle won','message'=>'Wild '.$state['wild']['display_name'].' was defeated.','exp'=>$exp,'money'=>$money];
    pv_wild_log($state,'Wild '.$state['wild']['display_name'].' fainted. You won the battle!','good');
    pv_wild_log($state,'Battle rewards: '.$exp.' EXP for each participating Pokémon and ₽'.number_format($money).'.','good');
}

function pv_wild_finalize_loss(mysqli $db, array &$state): void
{
    if (($state['status'] ?? '') !== 'active') return;
    $uid=(int)$_SESSION['myid'];
    $battleId=(string)($state['id'] ?? '');
    $existing=pv_wild_result_row($db,$battleId,$uid);
    if($existing){
        if((string)$existing['outcome']==='lost'){
            $state['status']='lost';
            $state['result']=['title'=>'Battle lost','message'=>'Your team was defeated by wild '.$state['wild']['display_name'].'.','exp'=>0,'money'=>0];
            return;
        }
        throw new RuntimeException('This encounter has already been resolved.');
    }
    $db->begin_transaction();
    try{
        pv_wild_result_insert($db,$state,$uid,'lost',0,0,0);
        $stmt=$db->prepare('UPDATE members SET losses=losses+1 WHERE id=?');
        if(!$stmt) throw new RuntimeException('Could not record the battle result.');
        $stmt->bind_param('i',$uid);$stmt->execute();$stmt->close();
        $db->commit();
    }catch(Throwable $e){
        $db->rollback();
        $existing=pv_wild_result_row($db,$battleId,$uid);
        if(!$existing || (string)$existing['outcome']!=='lost'){
            pv_log('Wild battle defeat ledger failure: '.$e->getMessage());
            throw new RuntimeException('The battle result could not be saved. Return to the map and try again.');
        }
    }
    $state['status']='lost';
    $state['result']=['title'=>'Battle lost','message'=>'Your team was defeated by wild '.$state['wild']['display_name'].'.','exp'=>0,'money'=>0];
    pv_wild_log($state,'Your team can no longer battle. Return to the map and regroup.','danger');
}

function pv_wild_item_catalog(): array
{
    return [
        'Potion'=>['column'=>'potion','heal'=>20],
        'Super Potion'=>['column'=>'super_potion','heal'=>100],
        'Hyper Potion'=>['column'=>'hyper_potion','heal'=>250],
    ];
}

function pv_wild_ball_catalog(): array
{
    return [
        'Poke Ball'=>['column'=>'poke_ball','base'=>0.22],
        'Great Ball'=>['column'=>'great_ball','base'=>0.38],
        'Ultra Ball'=>['column'=>'ultra_ball','base'=>0.56],
        'Master Ball'=>['column'=>'master_ball','base'=>1.0],
    ];
}

function pv_wild_inventory(mysqli $db, int $uid): array
{
    $stmt=$db->prepare('SELECT potion,super_potion,hyper_potion,poke_ball,great_ball,ultra_ball,master_ball FROM items WHERE uid=? LIMIT 1');
    if(!$stmt) return [];
    $stmt->bind_param('i',$uid);$stmt->execute();$row=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();
    return $row;
}

function pv_wild_consume(mysqli $db, int $uid, string $column): bool
{
    $allowed=['potion','super_potion','hyper_potion','poke_ball','great_ball','ultra_ball','master_ball'];
    if(!in_array($column,$allowed,true)) return false;
    $sql='UPDATE items SET `'.$column.'`=`'.$column.'`-1 WHERE uid=? AND `'.$column.'`>0';
    $stmt=$db->prepare($sql); if(!$stmt) return false;
    $stmt->bind_param('i',$uid);$ok=$stmt->execute() && $stmt->affected_rows===1;$stmt->close();
    return $ok;
}

function pv_wild_use_heal(mysqli $db, array &$state, string $item): void
{
    $catalog=pv_wild_item_catalog();
    if(!isset($catalog[$item])) throw new RuntimeException('Choose a valid battle medicine.');
    $activeId=(int)$state['active_id'];
    $player =& $state['team'][$activeId];
    if((int)$player['hp']<=0) throw new RuntimeException('A fainted Pokémon cannot use battle medicine.');
    if((int)$player['hp']>=(int)$player['max_hp']) throw new RuntimeException($player['name'].' is already at full HP.');
    if(!pv_wild_consume($db,(int)$_SESSION['myid'],$catalog[$item]['column'])) throw new RuntimeException('You do not have that item in your inventory.');
    $before=(int)$player['hp'];
    $player['hp']=min((int)$player['max_hp'],$before+(int)$catalog[$item]['heal']);
    $state['fx']['heal']=['item'=>$item,'amount'=>(int)($player['hp']-$before)];
    pv_wild_log($state,'You used '.$item.'. '.$player['name'].' recovered '.($player['hp']-$before).' HP.','good');
    pv_wild_enemy_turn($db,$state);
}

function pv_wild_gender(string $name): string
{
    $plain=preg_replace('/^(Shiny|Dark|Mystic|Shadow|Metallic)\s+/i','',$name) ?: $name;
    $genderless=['Magnemite','Magneton','Voltorb','Electrode','Staryu','Starmie','Porygon','Porygon2','Porygon-Z','Shedinja','Lunatone','Solrock','Baltoy','Claydol','Beldum','Metang','Metagross','Bronzor','Bronzong','Magnezone','Rotom','Phione','Manaphy','Klink','Klang','Klinklang','Cryogonal','Golett','Golurk','Carbink','Ditto','Articuno','Zapdos','Moltres','Mewtwo','Mew','Unown','Raikou','Entei','Suicune','Lugia','Celebi','Regirock','Regice','Registeel','Kyogre','Groudon','Rayquaza','Jirachi','Deoxys','Uxie','Mesprit','Azelf','Dialga','Palkia','Regigigas','Giratina','Darkrai','Shaymin','Arceus','Victini','Cobalion','Terrakion','Virizion','Reshiram','Zekrom','Kyurem','Genesect','Xerneas','Yveltal','Zygarde'];
    if(in_array($plain,$genderless,true)) return 'None';
    return random_int(1,2)===1?'Male':'Female';
}

function pv_wild_capture_create(mysqli $db, array $state, string $ball): int
{
    $uid=(int)$_SESSION['myid']; $username=(string)($_SESSION['myuser']??'Trainer');
    $wild=$state['wild']; $pid=(int)$wild['pid'];
    $stmt=$db->prepare('SELECT id,name,a1,a2,a3,a4,type1,type2 FROM pguide WHERE id=? LIMIT 1 FOR UPDATE');
    if(!$stmt) throw new RuntimeException('Captured Pokémon data could not be loaded.');
    $stmt->bind_param('i',$pid);$stmt->execute();$guide=$stmt->get_result()->fetch_assoc();$stmt->close();
    if(!$guide) throw new RuntimeException('Captured Pokémon data is unavailable.');
    $name=(string)$guide['name'];$level=max(1,(int)$wild['level']);$exp=$level*500;$gender=pv_wild_gender($name);
    $a1=(string)$guide['a1'];$a2=(string)$guide['a2'];$a3=(string)$guide['a3'];$a4=(string)$guide['a4'];$t1=(string)$guide['type1'];$t2=(string)$guide['type2'];
    $stmt=$db->prepare('INSERT INTO pokemon (name,pid,owner,a1,a2,a3,a4,lvl,t1,t2,exp,rowner,ball,gender,ot) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
    if(!$stmt) throw new RuntimeException('The captured Pokémon could not be created.');
    $stmt->bind_param('siissssississss',$name,$pid,$uid,$a1,$a2,$a3,$a4,$level,$t1,$t2,$exp,$username,$ball,$gender,$username);
    if(!$stmt->execute()){ $stmt->close(); throw new RuntimeException('The captured Pokémon could not be saved.'); }
    $pokemonId=(int)$db->insert_id;$stmt->close();

    $ivs=array_map(static fn()=>random_int(0,31),range(1,6));[$hp,$atk,$def,$spa,$spd,$spe]=$ivs;
    $natures=['Hardy','Lonely','Brave','Adamant','Naughty','Bold','Docile','Relaxed','Impish','Lax','Timid','Hasty','Serious','Jolly','Naive','Modest','Mild','Quiet','Bashful','Rash','Calm','Gentle','Sassy','Careful','Quirky'];
    $nature=$natures[random_int(0,count($natures)-1)];
    $ability='';
    $stmt=$db->prepare('SELECT ability1,ability2,ability3 FROM abilities WHERE name=? LIMIT 1');
    if($stmt){$stmt->bind_param('s',$name);$stmt->execute();$row=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();$pool=array_values(array_filter([(string)($row['ability1']??''),(string)($row['ability2']??''),(string)($row['ability3']??'')],static fn($v)=>$v!==''));if($pool)$ability=$pool[random_int(0,count($pool)-1)];}
    if($ability===''){
        $base=preg_replace('/^(Shiny|Dark|Mystic|Shadow|Metallic)\s+/i','',$name)?:$name;
        $stmt=$db->prepare('SELECT ability1,ability2,ability3 FROM abilities WHERE name=? LIMIT 1');
        if($stmt){$stmt->bind_param('s',$base);$stmt->execute();$row=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();$pool=array_values(array_filter([(string)($row['ability1']??''),(string)($row['ability2']??''),(string)($row['ability3']??'')],static fn($v)=>$v!==''));if($pool)$ability=$pool[random_int(0,count($pool)-1)];}
    }
    $displayForm=trim((string)($wild['display_name']??''));
    if($displayForm==='' || strcasecmp($displayForm,$name)===0) $displayForm='';
    $stmt=$db->prepare('INSERT INTO pokemon_stats (id,hp_iv,attack_iv,defense_iv,spatk_iv,spdef_iv,speed_iv,nature,ability,ot,gender,ball,happiness,display_form) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,0,?)');
    if(!$stmt) throw new RuntimeException('Captured Pokémon stats could not be created.');
    $stmt->bind_param('iiiiiiissssss',$pokemonId,$hp,$atk,$def,$spa,$spd,$spe,$nature,$ability,$username,$gender,$ball,$displayForm);
    if(!$stmt->execute()){ $stmt->close(); throw new RuntimeException('Captured Pokémon stats could not be saved.'); }$stmt->close();
    $stmt=$db->prepare('UPDATE pguide SET amount=amount+1 WHERE id=?');if($stmt){$stmt->bind_param('i',$pid);$stmt->execute();$stmt->close();}
    return $pokemonId;
}

function pv_wild_throw_ball(mysqli $db, array &$state, string $ball): void
{
    $catalog=pv_wild_ball_catalog();
    if(!isset($catalog[$ball])) throw new RuntimeException('Choose a valid Poké Ball.');
    $uid=(int)$_SESSION['myid'];
    $battleId=(string)($state['id'] ?? '');
    $existing=pv_wild_result_row($db,$battleId,$uid);
    if($existing){
        if((string)$existing['outcome']==='captured'){
            $state['status']='captured';
            $state['result']=['title'=>'Pokémon captured','message'=>$state['wild']['display_name'].' was captured.','pokemon_id'=>(int)$existing['captured_pokemon_id'],'exp'=>0,'money'=>0];
            return;
        }
        throw new RuntimeException('This encounter has already been resolved.');
    }

    $caught=false;$pokemonId=0;
    $db->begin_transaction();
    try {
        if(!pv_wild_consume($db,$uid,$catalog[$ball]['column'])) throw new RuntimeException('You do not have that Poké Ball in your inventory.');
        $wild=$state['wild'];
        $hpRatio=max(0.0,min(1.0,(float)$wild['hp']/max(1,(int)$wild['max_hp'])));
        $missing=1.0-$hpRatio;
        $levelPenalty=max(0.0,((int)$wild['level']-25)*0.003);
        $chance=(float)$catalog[$ball]['base'];
        if($chance<1.0) $chance=max(0.08,min(0.95,$chance+($missing*0.48)-$levelPenalty));
        $caught=$chance>=1.0 || (random_int(1,10000)/10000)<=$chance;
        if($caught){
            $pokemonId=pv_wild_capture_create($db,$state,$ball);
            pv_wild_result_insert($db,$state,$uid,'captured',0,0,$pokemonId);
        }
        $db->commit();
    } catch(Throwable $e){
        $db->rollback();
        $existing=pv_wild_result_row($db,$battleId,$uid);
        if($existing && (string)$existing['outcome']==='captured'){
            $caught=true;$pokemonId=(int)$existing['captured_pokemon_id'];
        }else{
            if($e instanceof RuntimeException) throw $e;
            pv_log('Wild capture failure: '.$e->getMessage());
            throw new RuntimeException('The capture could not be completed. Please try again.');
        }
    }

    $state['fx']['capture']=['ball'=>$ball,'caught'=>$caught];
    if($caught){
        try { pv_recalculate_trainer_progress($db,$uid,true); }
        catch(Throwable $e){ pv_log('Wild capture progress refresh failed after committed capture: '.$e->getMessage()); }
        $state['status']='captured';
        $state['result']=['title'=>'Pokémon captured','message'=>$state['wild']['display_name'].' was caught with a '.$ball.'!','pokemon_id'=>$pokemonId,'exp'=>0,'money'=>0];
        pv_wild_log($state,'Click… click… caught! Wild '.$state['wild']['display_name'].' joined your collection.','good');
    } else {
        pv_wild_log($state,'You threw a '.$ball.', but wild '.$state['wild']['display_name'].' broke free.','danger');
        pv_wild_enemy_turn($db,$state);
    }
}

function pv_wild_switch(mysqli $db, array &$state, int $pokemonId): void
{
    if(!isset($state['team'][$pokemonId])) throw new RuntimeException('That Pokémon is not in this battle team.');
    if((int)$state['team'][$pokemonId]['hp']<=0) throw new RuntimeException('A fainted Pokémon cannot be switched in.');
    if($pokemonId===(int)$state['active_id']) throw new RuntimeException('That Pokémon is already active.');
    $state['active_id']=$pokemonId;$state['participants'][$pokemonId]=true;
    $state['fx']['switch']=['pokemon_id'=>$pokemonId,'name'=>(string)$state['team'][$pokemonId]['name']];
    pv_wild_log($state,'Go, '.$state['team'][$pokemonId]['name'].'!','accent');
    pv_wild_enemy_turn($db,$state);
}

function pv_wild_handle_action(mysqli $db, array $state, array $post): array
{
    if(($state['status']??'')!=='active') return $state;
    $submittedTurn=(int)($post['battle_turn']??0);
    $currentTurn=max(1,(int)($state['turn']??1));
    if($submittedTurn!==$currentTurn) throw new RuntimeException('That action came from an older turn. The current battle has been refreshed.');
    $action=(string)($post['battle_action']??'');
    $detail=match($action){
        'attack'=>trim((string)($post['move']??'')),
        'heal'=>trim((string)($post['item']??'')),
        'ball'=>trim((string)($post['ball']??'')),
        'switch'=>(string)max(0,(int)($post['pokemon_id']??0)),
        default=>'',
    };
    $state['fx']=[
        'id'=>bin2hex(random_bytes(6)),'turn'=>$currentTurn,'action'=>$action,'detail'=>$detail,
        'player'=>null,'enemy'=>null,'capture'=>null,'heal'=>null,'switch'=>null,'created_at'=>time(),
    ];
    switch($action){
        case 'attack':
            pv_wild_attack_turn($db,$state,(int)$state['active_id'],trim((string)($post['move']??'')));
            break;
        case 'heal':
            pv_wild_use_heal($db,$state,trim((string)($post['item']??'')));
            break;
        case 'ball':
            pv_wild_throw_ball($db,$state,trim((string)($post['ball']??'')));
            break;
        case 'switch':
            pv_wild_switch($db,$state,(int)($post['pokemon_id']??0));
            break;
        case 'run':
            $state['status']='ran';$state['result']=['title'=>'Battle ended','message'=>'You safely withdrew from the encounter.','exp'=>0,'money'=>0];
            pv_wild_log($state,'You escaped from wild '.$state['wild']['display_name'].'.','muted');
            break;
        default:
            throw new RuntimeException('Choose a battle action.');
    }
    $state['turn']=max(1,(int)$state['turn']+1);$state['updated_at']=time();pv_wild_save($state);return $state;
}
